//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.App.Resources.FormMessages.FrmProductionByPayloadSocket {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrmProductionByPayloadSocketMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrmProductionByPayloadSocketMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.App.Resources.FormMessages.FrmProductionByPayloadSocket.FrmProduct" +
                            "ionByPayloadSocketMessages", typeof(FrmProductionByPayloadSocketMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Produção | Ação: {1} | Erro: {2}.
        /// </summary>
        internal static string ACTION_ERROR_LOG {
            get {
                return ResourceManager.GetString("ACTION_ERROR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máquina Pronta.
        /// </summary>
        internal static string ALARMS_LIST_UPDATE_HANDLER_TEXT_1 {
            get {
                return ResourceManager.GetString("ALARMS_LIST_UPDATE_HANDLER_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovado.
        /// </summary>
        internal static string APPROVED_MESSAGE {
            get {
                return ResourceManager.GetString("APPROVED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando início da produção.
        /// </summary>
        internal static string AWAITING_PRODUCTION_START_MESSAGE {
            get {
                return ResourceManager.GetString("AWAITING_PRODUCTION_START_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automático.
        /// </summary>
        internal static string BTN_AUTOMATIC_CAPTION_AUTOMATIC {
            get {
                return ResourceManager.GetString("BTN_AUTOMATIC_CAPTION_AUTOMATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string BTN_AUTOMATIC_CAPTION_MANUAL {
            get {
                return ResourceManager.GetString("BTN_AUTOMATIC_CAPTION_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando itens.
        /// </summary>
        internal static string BTN_CLEAR_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_CLEAR_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão LIMPAR.
        /// </summary>
        internal static string BTN_CLEAR_TEXT_2 {
            get {
                return ResourceManager.GetString("BTN_CLEAR_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpando fila.
        /// </summary>
        internal static string BTN_CLEAR_TEXT_3 {
            get {
                return ResourceManager.GetString("BTN_CLEAR_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar Ordem de Produção.
        /// </summary>
        internal static string BTN_FINISH_PRODUCTION_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_FINISH_PRODUCTION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há itens pendentes de produção na Ordem de Produção selecionada.\r\nTem certeza que deseja finalizar esta ordem?.
        /// </summary>
        internal static string BTN_FINISH_PRODUCTION_TEXT_2 {
            get {
                return ResourceManager.GetString("BTN_FINISH_PRODUCTION_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma Ordem de Produção selecionada..
        /// </summary>
        internal static string BTN_FINISH_PRODUCTION_TEXT_3 {
            get {
                return ResourceManager.GetString("BTN_FINISH_PRODUCTION_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Finalizar Ordem de Produção.
        /// </summary>
        internal static string BTN_FINISH_PRODUCTION_TEXT_4 {
            get {
                return ResourceManager.GetString("BTN_FINISH_PRODUCTION_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Reset.
        /// </summary>
        internal static string BTN_RESET_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_RESET_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar.
        /// </summary>
        internal static string BTN_START_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produção iniciada.
        /// </summary>
        internal static string BTN_START_TEXT_2 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Ordem:.
        /// </summary>
        internal static string BTN_START_TEXT_3 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de itens.
        /// </summary>
        internal static string BTN_START_TEXT_4 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itens produzidos.
        /// </summary>
        internal static string BTN_START_TEXT_5 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja iniciar a ordem de produção abaixo?.
        /// </summary>
        internal static string BTN_START_TEXT_6 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de Início de Produção:.
        /// </summary>
        internal static string BTN_START_TEXT_7 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Iniciar/Parar.
        /// </summary>
        internal static string BTN_START_TEXT_8 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar.
        /// </summary>
        internal static string BTN_START_TEXT_9 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando itens.
        /// </summary>
        internal static string CB_PRODUCTION_ORDER_TEXT_1 {
            get {
                return ResourceManager.GetString("CB_PRODUCTION_ORDER_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela Produção carregada.
        /// </summary>
        internal static string CONSTRUCTOR_TEXT_1 {
            get {
                return ResourceManager.GetString("CONSTRUCTOR_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to itens impressos.
        /// </summary>
        internal static string DISPLAY_PRINTED_ITEMS_TEXT_1 {
            get {
                return ResourceManager.GetString("DISPLAY_PRINTED_ITEMS_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string FINISH_PRODUCTION_ERROR_1 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao finalizar Ordem de Produção.
        /// </summary>
        internal static string FINISH_PRODUCTION_ERROR_2 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso.
        /// </summary>
        internal static string FINISH_PRODUCTION_TEXT_1 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem de Produção finalizada com sucesso!.
        /// </summary>
        internal static string FINISH_PRODUCTION_TEXT_2 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to em &apos;Sim&apos; para finalizar a Ordem de Produção.
        /// </summary>
        internal static string FINISH_PRODUCTION_TEXT_3 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com itens pendentes.
        /// </summary>
        internal static string FINISH_PRODUCTION_TEXT_4 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading da tela de Produção.
        /// </summary>
        internal static string FROM_LOAD_TEXT_1 {
            get {
                return ResourceManager.GetString("FROM_LOAD_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string FROM_LOAD_TEXT_2 {
            get {
                return ResourceManager.GetString("FROM_LOAD_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Máquina.
        /// </summary>
        internal static string LABELED_PANEL_MACHINE_STATUS {
            get {
                return ResourceManager.GetString("LABELED_PANEL_MACHINE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Produção.
        /// </summary>
        internal static string LABELED_PANEL_PRODUCTION_STATUS {
            get {
                return ResourceManager.GetString("LABELED_PANEL_PRODUCTION_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para iniciar, altere o modo de produção para Automático na IHM.
        /// </summary>
        internal static string MANUAL_MODE_LOCK_MESSAGE {
            get {
                return ResourceManager.GetString("MANUAL_MODE_LOCK_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produção bloqueada.
        /// </summary>
        internal static string MANUAL_MODE_LOCK_TITLE {
            get {
                return ResourceManager.GetString("MANUAL_MODE_LOCK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação não permitida.
        /// </summary>
        internal static string MSGBOX_ACTION_NOT_ALLOWED_TITLE {
            get {
                return ResourceManager.GetString("MSGBOX_ACTION_NOT_ALLOWED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câmera Identificação.
        /// </summary>
        internal static string MULTI_LABEL_CAMERA_IDENTIFICATION_TEXT_1 {
            get {
                return ResourceManager.GetString("MULTI_LABEL_CAMERA_IDENTIFICATION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câmera Superior.
        /// </summary>
        internal static string MULTI_LABEL_CAMERA_IDENTIFICATION_TEXT_2 {
            get {
                return ResourceManager.GetString("MULTI_LABEL_CAMERA_IDENTIFICATION_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câmera Lateral.
        /// </summary>
        internal static string MULTI_LABEL_CAMERA_IDENTIFICATION_TEXT_3 {
            get {
                return ResourceManager.GetString("MULTI_LABEL_CAMERA_IDENTIFICATION_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para iniciar, selecione Ordem de Produção.
        /// </summary>
        internal static string NO_SELECTED_PARAMETERS_MESSAGE {
            get {
                return ResourceManager.GetString("NO_SELECTED_PARAMETERS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum parâmetro selecionado.
        /// </summary>
        internal static string NO_SELECTED_PARAMETERS_TITLE {
            get {
                return ResourceManager.GetString("NO_SELECTED_PARAMETERS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar Lote.
        /// </summary>
        internal static string PCB_BATCH_CODE_TEXT_1 {
            get {
                return ResourceManager.GetString("PCB_BATCH_CODE_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão para selecionar o lote.
        /// </summary>
        internal static string PCB_BATCH_CODE_TEXT_2 {
            get {
                return ResourceManager.GetString("PCB_BATCH_CODE_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar Produto.
        /// </summary>
        internal static string PCB_SEARCH_PRODUCT_TEXT_1 {
            get {
                return ResourceManager.GetString("PCB_SEARCH_PRODUCT_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão para selecionar o produto.
        /// </summary>
        internal static string PCB_SEARCH_PRODUCT_TEXT_2 {
            get {
                return ResourceManager.GetString("PCB_SEARCH_PRODUCT_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão para selecionar a ordem de produção.
        /// </summary>
        internal static string PIC_SEARCH_PRODUCTION_ORDER_TEXT_1 {
            get {
                return ResourceManager.GetString("PIC_SEARCH_PRODUCTION_ORDER_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressora não conectada. Para iniciar, verifique conexão..
        /// </summary>
        internal static string PRINTER_NOT_CONNECTED_MESSAGE {
            get {
                return ResourceManager.GetString("PRINTER_NOT_CONNECTED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressora não conectada.
        /// </summary>
        internal static string PRINTER_NOT_CONNECTED_TITLE {
            get {
                return ResourceManager.GetString("PRINTER_NOT_CONNECTED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejeitado - Sem leitura.
        /// </summary>
        internal static string REJECTED_NO_READ_MESSAGE {
            get {
                return ResourceManager.GetString("REJECTED_NO_READ_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronização concluída.
        /// </summary>
        internal static string SYNC__DATA_TEXT_2 {
            get {
                return ResourceManager.GetString("SYNC _DATA_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string SYNC_DATA_ERROR {
            get {
                return ResourceManager.GetString("SYNC_DATA_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados sincronizados com sucesso.
        /// </summary>
        internal static string SYNC_DATA_TEXT_1 {
            get {
                return ResourceManager.GetString("SYNC_DATA_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronização concluída.
        /// </summary>
        internal static string SYNC_DATA_TEXT_2 {
            get {
                return ResourceManager.GetString("SYNC_DATA_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificou estado de ckBtnStart.
        /// </summary>
        internal static string TOGGLE_BTN_START_TEXT_1 {
            get {
                return ResourceManager.GetString("TOGGLE_BTN_START_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificou estado de ckBtnStart para.
        /// </summary>
        internal static string TOGGLE_BTN_START_TEXT_2 {
            get {
                return ResourceManager.GetString("TOGGLE_BTN_START_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câmera Validação.
        /// </summary>
        internal static string TRIPLE_LABEL_CAMERA_VALIDATION_TEXT_1 {
            get {
                return ResourceManager.GetString("TRIPLE_LABEL_CAMERA_VALIDATION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produção.
        /// </summary>
        internal static string TRIPLE_LABEL_PRODUCTION_TEXT_1 {
            get {
                return ResourceManager.GetString("TRIPLE_LABEL_PRODUCTION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itens.
        /// </summary>
        internal static string TRIPLE_LABEL_PRODUCTION_TEXT_2 {
            get {
                return ResourceManager.GetString("TRIPLE_LABEL_PRODUCTION_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidade.
        /// </summary>
        internal static string TRIPLE_LABEL_SPEED_TEXT_1 {
            get {
                return ResourceManager.GetString("TRIPLE_LABEL_SPEED_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itens por minuto.
        /// </summary>
        internal static string TRIPLE_LABEL_SPEED_TEXT_2 {
            get {
                return ResourceManager.GetString("TRIPLE_LABEL_SPEED_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Produção | Ação: {1}.
        /// </summary>
        internal static string USER_ACTION_LOG {
            get {
                return ResourceManager.GetString("USER_ACTION_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Produção | Ação: Clicou {1}.
        /// </summary>
        internal static string USER_CLICK_LOG {
            get {
                return ResourceManager.GetString("USER_CLICK_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Produção | Tentativa de INICIAR/PARAR produção sem permissão. Ação não autorizada..
        /// </summary>
        internal static string USER_CLICK_REGISTERS_LOG_PRODUCTION_STARTED_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("USER_CLICK_REGISTERS_LOG_PRODUCTION_STARTED_NOT_ALLOWED", resourceCulture);
            }
        }
    }
}
