//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.App.Resources.FormMessages.frmProductionStartValidation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class frmProductionStartValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmProductionStartValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.App.Resources.FormMessages.frmProductionStartValidation.frmProduct" +
                            "ionStartValidationMessages", typeof(frmProductionStartValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Validação da Produção | Ação: {1} | Erro: {2}.
        /// </summary>
        internal static string ACTION_ERROR_LOG {
            get {
                return ResourceManager.GetString("ACTION_ERROR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Cancelar.
        /// </summary>
        internal static string BTN_CANCEL_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_CANCEL_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND_BY_USERNAME_ERROR_1.
        /// </summary>
        internal static string BTN_YES_LOG_1 {
            get {
                return ResourceManager.GetString("BTN_YES_LOG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão SIM.
        /// </summary>
        internal static string BTN_YES_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_YES_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário sem permissão para iniciar a produção.
        /// </summary>
        internal static string FIND_BY_USERNAME_ERROR_1 {
            get {
                return ResourceManager.GetString("FIND_BY_USERNAME_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário desabilitado.
        /// </summary>
        internal static string FIND_BY_USERNAME_ERROR_2 {
            get {
                return ResourceManager.GetString("FIND_BY_USERNAME_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário inválido - Não encontrado..
        /// </summary>
        internal static string FIND_BY_USERNAME_ERROR_3 {
            get {
                return ResourceManager.GetString("FIND_BY_USERNAME_ERROR_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao autenticar o usuário para iniciar a produção.
        /// </summary>
        internal static string GENERIC_ERROR {
            get {
                return ResourceManager.GetString("GENERIC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro não identificado.
        /// </summary>
        internal static string GENERIC_ERROR_TITLE {
            get {
                return ResourceManager.GetString("GENERIC_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja iniciar a produção?.
        /// </summary>
        internal static string LOAD_TEXT_ON_SCREEN_TEXT_1 {
            get {
                return ResourceManager.GetString("LOAD_TEXT_ON_SCREEN_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro: Login inválido.
        /// </summary>
        internal static string LOGIN_ERROR_TITLE {
            get {
                return ResourceManager.GetString("LOGIN_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Validação da Produção | Ação: Produto {1} validado com sucesso.
        /// </summary>
        internal static string PRODUCTION_ITEMS_LOG {
            get {
                return ResourceManager.GetString("PRODUCTION_ITEMS_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Validação da Produção | Ação: {1}.
        /// </summary>
        internal static string USER_ACTION_LOG {
            get {
                return ResourceManager.GetString("USER_ACTION_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Validação da Produção | Ação: Clicou {1}.
        /// </summary>
        internal static string USER_CLICK_LOG {
            get {
                return ResourceManager.GetString("USER_CLICK_LOG", resourceCulture);
            }
        }
    }
}
