//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.App.Resources.FormMessages.FrmReportAlarms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrmReportAlarmsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrmReportAlarmsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.App.Resources.FormMessages.FrmReportAlarms.FrmReportAlarmsMessages" +
                            "", typeof(FrmReportAlarmsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Relatório de Alarmes | Ação: {1} | Erro: {2}.
        /// </summary>
        internal static string ACTION_ERROR_LOG {
            get {
                return ResourceManager.GetString("ACTION_ERROR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao gerar relatório de logs.
        /// </summary>
        internal static string BTN_REPORT_ALARM_EXPORT_ERROR_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_REPORT_ALARM_EXPORT_ERROR_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string BTN_REPORT_ALARM_EXPORT_ERROR_TEXT_2 {
            get {
                return ResourceManager.GetString("BTN_REPORT_ALARM_EXPORT_ERROR_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatório exportado.
        /// </summary>
        internal static string BTN_REPORT_ALARM_EXPORT_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_REPORT_ALARM_EXPORT_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Exportar Relatório de Alarmes.
        /// </summary>
        internal static string BTN_REPORT_ALARM_EXPORT_TEXT_2 {
            get {
                return ResourceManager.GetString("BTN_REPORT_ALARM_EXPORT_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clicou no botão Filtrar.
        /// </summary>
        internal static string BTN_REPORT_ALARM_FILTER_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_REPORT_ALARM_FILTER_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no cabeçalho da coluna.
        /// </summary>
        internal static string DG_ALARMS_TEXT_1 {
            get {
                return ResourceManager.GetString("DG_ALARMS_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to para reordenar.
        /// </summary>
        internal static string DG_ALARMS_TEXT_2 {
            get {
                return ResourceManager.GetString("DG_ALARMS_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregamento da tela de Relatório de Alarms.
        /// </summary>
        internal static string FORM_LOAD_TEXT_1 {
            get {
                return ResourceManager.GetString("FORM_LOAD_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um problema ao tentar executar esta ação.
        /// </summary>
        internal static string GENERIC_ERROR {
            get {
                return ResourceManager.GetString("GENERIC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro não identificado.
        /// </summary>
        internal static string GENERIC_ERROR_TITLE {
            get {
                return ResourceManager.GetString("GENERIC_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar informações.
        /// </summary>
        internal static string GET_ALARMS_ERROR_TEXT_1 {
            get {
                return ResourceManager.GetString("GET_ALARMS_ERROR_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string GET_ALARMS_ERROR_TEXT_2 {
            get {
                return ResourceManager.GetString("GET_ALARMS_ERROR_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro aplicado.
        /// </summary>
        internal static string GET_ALARMS_TEXT_1 {
            get {
                return ResourceManager.GetString("GET_ALARMS_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu nível de acesso [{0}] não possui autorização para realizar todas as ações deste formulário.
        /// </summary>
        internal static string MSGBOX_ACTION_LIMITED_ALLOWED {
            get {
                return ResourceManager.GetString("MSGBOX_ACTION_LIMITED_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {3} | Tela: Relatório de Alarmes | Relatório Gerado - Data-Hora Inicial: {1}, Data-Hora Final: {2}.
        /// </summary>
        internal static string REPORT_LOG {
            get {
                return ResourceManager.GetString("REPORT_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Relatório de Alarmes | Ação: {1}.
        /// </summary>
        internal static string USER_ACTION_LOG {
            get {
                return ResourceManager.GetString("USER_ACTION_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Relatório de Alarmes | Ação: Clicou {1}.
        /// </summary>
        internal static string USER_CLICK_LOG {
            get {
                return ResourceManager.GetString("USER_CLICK_LOG", resourceCulture);
            }
        }
    }
}
