//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.DataBaseUtility.Resources.DataBaseUtilityExternalService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataBaseUtilityExternalServiceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataBaseUtilityExternalServiceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.DataBaseUtility.Resources.DataBaseUtilityExternalService.DataBaseU" +
                            "tilityExternalServiceMessages", typeof(DataBaseUtilityExternalServiceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na criação de backup não criptografado.
        /// </summary>
        internal static string CREATE_BACKUP_ERROR_1 {
            get {
                return ResourceManager.GetString("CREATE_BACKUP_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissionamento para usuario.
        /// </summary>
        internal static string CREATE_BACKUP_TEXT_1 {
            get {
                return ResourceManager.GetString("CREATE_BACKUP_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to realizado com sucesso.
        /// </summary>
        internal static string CREATE_BACKUP_TEXT_2 {
            get {
                return ResourceManager.GetString("CREATE_BACKUP_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao realizar permissionamento para backup em.
        /// </summary>
        internal static string CREATE_BACKUP_TEXT_3 {
            get {
                return ResourceManager.GetString("CREATE_BACKUP_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup não criptografado criado com sucesso em {0} - Usuário: {1}.
        /// </summary>
        internal static string CREATE_BACKUP_TEXT_4 {
            get {
                return ResourceManager.GetString("CREATE_BACKUP_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na criação de backup não criptografado. Código.
        /// </summary>
        internal static string CREATE_BACKUP_TEXT_5 {
            get {
                return ResourceManager.GetString("CREATE_BACKUP_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem de Erro.
        /// </summary>
        internal static string CREATE_BACKUP_TEXT_6 {
            get {
                return ResourceManager.GetString("CREATE_BACKUP_TEXT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nula.
        /// </summary>
        internal static string CREATE_BACKUP_TEXT_7 {
            get {
                return ResourceManager.GetString("CREATE_BACKUP_TEXT_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na criação de backup criptografado.
        /// </summary>
        internal static string CREATE_ENCRYPTED_BACKUP_ERROR_1 {
            get {
                return ResourceManager.GetString("CREATE_ENCRYPTED_BACKUP_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando criação de backup criptografado - Usuário {0}.
        /// </summary>
        internal static string CREATE_ENCRYPTED_BACKUP_TEXT_1 {
            get {
                return ResourceManager.GetString("CREATE_ENCRYPTED_BACKUP_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup criado com sucesso: {0} - Usuário: {1}.
        /// </summary>
        internal static string CREATE_ENCRYPTED_BACKUP_TEXT_2 {
            get {
                return ResourceManager.GetString("CREATE_ENCRYPTED_BACKUP_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup criado com sucesso.
        /// </summary>
        internal static string CREATE_ENCRYPTED_BACKUP_TEXT_3 {
            get {
                return ResourceManager.GetString("CREATE_ENCRYPTED_BACKUP_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decriptando backup.
        /// </summary>
        internal static string DENCRYPTED_BACKUP_TEXT_1 {
            get {
                return ResourceManager.GetString("DENCRYPTED_BACKUP_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup decriptado com sucesso.
        /// </summary>
        internal static string DENCRYPTED_BACKUP_TEXT_2 {
            get {
                return ResourceManager.GetString("DENCRYPTED_BACKUP_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando criptografia do backup.
        /// </summary>
        internal static string ENCRYPTED_BACKUP_TEXT_1 {
            get {
                return ResourceManager.GetString("ENCRYPTED_BACKUP_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup criptografado com sucesso.
        /// </summary>
        internal static string ENCRYPTED_BACKUP_TEXT_2 {
            get {
                return ResourceManager.GetString("ENCRYPTED_BACKUP_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao restaurar o backup.
        /// </summary>
        internal static string RESTORE_BACKUP_ERROR_1 {
            get {
                return ResourceManager.GetString("RESTORE_BACKUP_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurando backup.
        /// </summary>
        internal static string RESTORE_BACKUP_TEXT_1 {
            get {
                return ResourceManager.GetString("RESTORE_BACKUP_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup restaurado com sucesso.
        /// </summary>
        internal static string RESTORE_BACKUP_TEXT_2 {
            get {
                return ResourceManager.GetString("RESTORE_BACKUP_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na restauração de backup criptografado.
        /// </summary>
        internal static string RESTORE_ENCRYPTED_BACKUP_ERROR_1 {
            get {
                return ResourceManager.GetString("RESTORE_ENCRYPTED_BACKUP_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando restauração de backup criptografado - Usuário: {0}.
        /// </summary>
        internal static string RESTORE_ENCRYPTED_BACKUP_TEXT_1 {
            get {
                return ResourceManager.GetString("RESTORE_ENCRYPTED_BACKUP_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup restaurado com sucesso - Usuário: {0}.
        /// </summary>
        internal static string RESTORE_ENCRYPTED_BACKUP_TEXT_2 {
            get {
                return ResourceManager.GetString("RESTORE_ENCRYPTED_BACKUP_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup restaurado com sucesso.
        /// </summary>
        internal static string RESTORE_ENCRYPTED_BACKUP_TEXT_3 {
            get {
                return ResourceManager.GetString("RESTORE_ENCRYPTED_BACKUP_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações de conexão com base de dados adquiridas com sucesso.
        /// </summary>
        internal static string SET_DATABASE_SETTINGS_TEXT_1 {
            get {
                return ResourceManager.GetString("SET_DATABASE_SETTINGS_TEXT_1", resourceCulture);
            }
        }
    }
}
