//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.Machine.Resources.S7Driver {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class S7DriverMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal S7DriverMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.Machine.Resources.S7Driver.S7DriverMessages", typeof(S7DriverMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receita enviada: Velocidade {0}, Tamanho {1}, Atraso {2}, Rampa Acel {3}, Rampa Desac {4}, Filtro {5}.
        /// </summary>
        internal static string APPLICATOR_PRESET_LOG {
            get {
                return ResourceManager.GetString("APPLICATOR_PRESET_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLP Conectado.
        /// </summary>
        internal static string PLC_CONNECTED_MESSAGE {
            get {
                return ResourceManager.GetString("PLC_CONNECTED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLP Não Conectado.
        /// </summary>
        internal static string PLC_NOT_CONNECTED_MESSAGE {
            get {
                return ResourceManager.GetString("PLC_NOT_CONNECTED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESCRITAS NO CLP - CÉLULA = {0}\r\n{1}.
        /// </summary>
        internal static string PLC_WRITE_LOG_MESSAGE {
            get {
                return ResourceManager.GetString("PLC_WRITE_LOG_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENVIO PARA PLC - FUNÇÃO: {0} | DataBlock: {1} | Endereço: {2}.{3} | Valor: {4}.
        /// </summary>
        internal static string SENT_DATA_TO_PLC {
            get {
                return ResourceManager.GetString("SENT_DATA_TO_PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escrita de lifebit iniciada.
        /// </summary>
        internal static string START_LIFE_BIT_TEXT_1 {
            get {
                return ResourceManager.GetString("START_LIFE_BIT_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escrita de lifebit encerrada.
        /// </summary>
        internal static string START_LIFE_BIT_TEXT_2 {
            get {
                return ResourceManager.GetString("START_LIFE_BIT_TEXT_2", resourceCulture);
            }
        }
    }
}
