//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.App.Resources.FormMessages.FrmProductionByPO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrmProductionByPOMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrmProductionByPOMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.App.Resources.FormMessages.FrmProductionByPO.FrmProductionByPOMess" +
                            "ages", typeof(FrmProductionByPOMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Produção | Ação: {1} | Erro: {2}.
        /// </summary>
        internal static string ACTION_ERROR_LOG {
            get {
                return ResourceManager.GetString("ACTION_ERROR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máquina Pronta.
        /// </summary>
        internal static string ALARMAS_LIST_UPDATE_HANDLER_TEXT_1 {
            get {
                return ResourceManager.GetString("ALARMAS_LIST_UPDATE_HANDLER_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovado.
        /// </summary>
        internal static string APPROVED_MESSAGE {
            get {
                return ResourceManager.GetString("APPROVED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando início da produção.
        /// </summary>
        internal static string AWAITING_PRODUCTION_START_MESSAGE {
            get {
                return ResourceManager.GetString("AWAITING_PRODUCTION_START_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automático.
        /// </summary>
        internal static string BTN_AUTOMATIC_MODE_AUTOMATIC {
            get {
                return ResourceManager.GetString("BTN_AUTOMATIC_MODE_AUTOMATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string BTN_AUTOMATIC_MODE_MANUAL {
            get {
                return ResourceManager.GetString("BTN_AUTOMATIC_MODE_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar Ficha de Adequação.
        /// </summary>
        internal static string BTN_FINISH_PRODUCTION_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_FINISH_PRODUCTION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há itens pendentes de produção na ficha de adequação selecionada.\r\nTem certeza que deseja finalizar esta ficha?.
        /// </summary>
        internal static string BTN_FINISH_PRODUCTION_TEXT_2 {
            get {
                return ResourceManager.GetString("BTN_FINISH_PRODUCTION_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma Ficha de Adequação selecionada..
        /// </summary>
        internal static string BTN_FINISH_PRODUCTION_TEXT_3 {
            get {
                return ResourceManager.GetString("BTN_FINISH_PRODUCTION_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Finalizar Ficha de Adequação.
        /// </summary>
        internal static string BTN_FINISH_PRODUCTION_TEXT_4 {
            get {
                return ResourceManager.GetString("BTN_FINISH_PRODUCTION_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Reset.
        /// </summary>
        internal static string BTN_RESET_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_RESET_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produção iniciada.
        /// </summary>
        internal static string BTN_START_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar.
        /// </summary>
        internal static string BTN_START_TEXT_2 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você confirma que os itens acima estão de acordo com o solicitado?.
        /// </summary>
        internal static string BTN_START_TEXT_3 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha de Adequação.
        /// </summary>
        internal static string BTN_START_TEXT_4 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máquina com status de limpeza \&quot;Limpo\&quot; (sem resíduo de produtos/PO anteriores)\r\n• Máquina configurada para o produto correto\r\n• Pallet identificado\r\n• Apenas um PO/NF aguardando conferência.
        /// </summary>
        internal static string BTN_START_TEXT_5 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique as Informações Abaixo.
        /// </summary>
        internal static string BTN_START_TEXT_6 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de Início de Adequação:.
        /// </summary>
        internal static string BTN_START_TEXT_7 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Iniciar/Parar.
        /// </summary>
        internal static string BTN_START_TEXT_8 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar.
        /// </summary>
        internal static string BTN_START_TEXT_9 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela Produção carregada.
        /// </summary>
        internal static string CONSTRUCTOR_TEXT_1 {
            get {
                return ResourceManager.GetString("CONSTRUCTOR_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string FINISH_PRODUCTION_ERROR_1 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao finalizar ficha de adequação.
        /// </summary>
        internal static string FINISH_PRODUCTION_ERROR_2 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao inserir itens na tabela de produção..
        /// </summary>
        internal static string FINISH_PRODUCTION_ERROR_3 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_ERROR_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso.
        /// </summary>
        internal static string FINISH_PRODUCTION_TEXT_1 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha de adequação finalizada com sucesso!.
        /// </summary>
        internal static string FINISH_PRODUCTION_TEXT_2 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to em &apos;Sim&apos; para finalizar a ficha de adequação.
        /// </summary>
        internal static string FINISH_PRODUCTION_TEXT_3 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com itens pendentes.
        /// </summary>
        internal static string FINISH_PRODUCTION_TEXT_4 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string FORM_LOAD_ERROR {
            get {
                return ResourceManager.GetString("FORM_LOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading da tela de Produção.
        /// </summary>
        internal static string FORM_LOAD_TEXT_1 {
            get {
                return ResourceManager.GetString("FORM_LOAD_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para iniciar, altere o modo de produção para Automático na IHM.
        /// </summary>
        internal static string MANUAL_MODE_LOCK_MESSAGE {
            get {
                return ResourceManager.GetString("MANUAL_MODE_LOCK_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produção bloqueada.
        /// </summary>
        internal static string MANUAL_MODE_LOCK_TITLE {
            get {
                return ResourceManager.GetString("MANUAL_MODE_LOCK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação não permitida.
        /// </summary>
        internal static string MSGBOX_ACTION_NOT_ALLOWED_TITLE {
            get {
                return ResourceManager.GetString("MSGBOX_ACTION_NOT_ALLOWED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para iniciar, selecione Ficha de Adequação.
        /// </summary>
        internal static string NO_SELECTED_PARAMETERS_MESSAGE {
            get {
                return ResourceManager.GetString("NO_SELECTED_PARAMETERS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum parâmetro selecionado.
        /// </summary>
        internal static string NO_SELECTED_PARAMETERS_TITLE {
            get {
                return ResourceManager.GetString("NO_SELECTED_PARAMETERS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro - Selecionar Lote.
        /// </summary>
        internal static string PCB_BATCH_CODE_ERROR {
            get {
                return ResourceManager.GetString("PCB_BATCH_CODE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão para selecionar o lote.
        /// </summary>
        internal static string PCB_BATCH_CODE_TEXT_1 {
            get {
                return ResourceManager.GetString("PCB_BATCH_CODE_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro - Selecionar Produto.
        /// </summary>
        internal static string PCB_SEARCH_PRODUCT_ERROR {
            get {
                return ResourceManager.GetString("PCB_SEARCH_PRODUCT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão para selecionar o produto.
        /// </summary>
        internal static string PCB_SEARCH_PRODUCT_TEXT_1 {
            get {
                return ResourceManager.GetString("PCB_SEARCH_PRODUCT_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão para selecionar a ordem de produção.
        /// </summary>
        internal static string PIC_SEARCH_PRODUCTION_ORDER_TEXT_1 {
            get {
                return ResourceManager.GetString("PIC_SEARCH_PRODUCTION_ORDER_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressora não conectada. Para iniciar, verifique conexão..
        /// </summary>
        internal static string PRINTER_NOT_CONNECTED_MESSAGE {
            get {
                return ResourceManager.GetString("PRINTER_NOT_CONNECTED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressora não conectada.
        /// </summary>
        internal static string PRINTER_NOT_CONNECTED_TITLE {
            get {
                return ResourceManager.GetString("PRINTER_NOT_CONNECTED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejeitado - Sem leitura.
        /// </summary>
        internal static string REJECTED_NO_READ_MESSAGE {
            get {
                return ResourceManager.GetString("REJECTED_NO_READ_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string SYNC_DATA_ERROR {
            get {
                return ResourceManager.GetString("SYNC_DATA_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificou estado de ckBtnStart.
        /// </summary>
        internal static string TOGGLE_BTN_START_ERROR {
            get {
                return ResourceManager.GetString("TOGGLE_BTN_START_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificou estado de ckBtnStart para.
        /// </summary>
        internal static string TOGGLE_BTN_START_TEXT_1 {
            get {
                return ResourceManager.GetString("TOGGLE_BTN_START_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Produção | Ação: {1}.
        /// </summary>
        internal static string USER_ACTION_LOG {
            get {
                return ResourceManager.GetString("USER_ACTION_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Produção | Ação: Clicou {1}.
        /// </summary>
        internal static string USER_CLICK_LOG {
            get {
                return ResourceManager.GetString("USER_CLICK_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Produção | Tentativa de INICIAR/PARAR produção sem permissão. Ação não autorizada..
        /// </summary>
        internal static string USER_CLICK_REGISTERS_LOG_PRODUCTION_STARTED_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("USER_CLICK_REGISTERS_LOG_PRODUCTION_STARTED_NOT_ALLOWED", resourceCulture);
            }
        }
    }
}
