//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.App.Resources.FormMessages.frmSettingDevices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class frmSettingDevicesMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmSettingDevicesMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.App.Resources.FormMessages.frmSettingDevices.frmSettingDevicesMess" +
                            "ages", typeof(frmSettingDevicesMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Configurações Dispositivos | Ação: {1} | Erro: {2}.
        /// </summary>
        internal static string ACTION_ERROR_LOG {
            get {
                return ResourceManager.GetString("ACTION_ERROR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Salvar.
        /// </summary>
        internal static string BTN_SAVE_SETTINGS_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_SAVE_SETTINGS_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desabilitado.
        /// </summary>
        internal static string CHK_LABEL_QUALITY_STATUS_1 {
            get {
                return ResourceManager.GetString("CHK_LABEL_QUALITY_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitado.
        /// </summary>
        internal static string CHK_LABEL_QUALITY_STATUS_2 {
            get {
                return ResourceManager.GetString("CHK_LABEL_QUALITY_STATUS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivos - Configurações.
        /// </summary>
        internal static string CONFIG_TITLE_1 {
            get {
                return ResourceManager.GetString("CONFIG_TITLE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao exibir dados de dispositivos na tela de configuração..
        /// </summary>
        internal static string FORM_LOAD_ERROR_1 {
            get {
                return ResourceManager.GetString("FORM_LOAD_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de dispositivos carregados na tela de configuração..
        /// </summary>
        internal static string FORM_LOAD_TEXT_1 {
            get {
                return ResourceManager.GetString("FORM_LOAD_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar as configurações dos dispositivos.
        /// </summary>
        internal static string SAVE_PROCESS_ERROR_1 {
            get {
                return ResourceManager.GetString("SAVE_PROCESS_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As alterações foram salvas com sucesso!\r\nPor favor, reinicie o software para que as mudanças tenham efeito..
        /// </summary>
        internal static string SAVE_PROCESS_TEXT_1 {
            get {
                return ResourceManager.GetString("SAVE_PROCESS_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitor de Validação.
        /// </summary>
        internal static string SAVE_PROCESS_TEXT_2 {
            get {
                return ResourceManager.GetString("SAVE_PROCESS_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitor de Reprocessamento.
        /// </summary>
        internal static string SAVE_PROCESS_TEXT_3 {
            get {
                return ResourceManager.GetString("SAVE_PROCESS_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitor de Entrada.
        /// </summary>
        internal static string SAVE_PROCESS_TEXT_4 {
            get {
                return ResourceManager.GetString("SAVE_PROCESS_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressora Manual.
        /// </summary>
        internal static string SAVE_PROCESS_TEXT_5 {
            get {
                return ResourceManager.GetString("SAVE_PROCESS_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressora Aplicador.
        /// </summary>
        internal static string SAVE_PROCESS_TEXT_6 {
            get {
                return ResourceManager.GetString("SAVE_PROCESS_TEXT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLP.
        /// </summary>
        internal static string SAVE_PROCESS_TEXT_7 {
            get {
                return ResourceManager.GetString("SAVE_PROCESS_TEXT_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Configurações Dispositivos | Ação: {1}.
        /// </summary>
        internal static string USER_ACTION_LOG {
            get {
                return ResourceManager.GetString("USER_ACTION_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Configurações Dispositivos | Ação: Clicou em {1}.
        /// </summary>
        internal static string USER_CLICK_LOG {
            get {
                return ResourceManager.GetString("USER_CLICK_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Configurações Dispositivos | Ação: Salvou configurações do dispositivo {1}.
        /// </summary>
        internal static string USER_SAVED_SETTINGS_LOG {
            get {
                return ResourceManager.GetString("USER_SAVED_SETTINGS_LOG", resourceCulture);
            }
        }
    }
}
