//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.App.Resources.FormMessages.RegisterZpl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegisterZplMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterZplMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.App.Resources.FormMessages.RegisterZpl.RegisterZplMessages", typeof(RegisterZplMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletando de layouts da etiqueta {0} pelo usuário {1}..
        /// </summary>
        internal static string BTN_REMOVE_ZPL_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_REMOVE_ZPL_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete template inválido..
        /// </summary>
        internal static string DELETE_PRINT_TEMPLATE_ERROR_TITLE {
            get {
                return ResourceManager.GetString("DELETE_PRINT_TEMPLATE_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossível deletar, o template da etiqueta esta sendo utilizado..
        /// </summary>
        internal static string DELETE_PRINT_TEMPLATE_EXHIST {
            get {
                return ResourceManager.GetString("DELETE_PRINT_TEMPLATE_EXHIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo deletar o registro do cadastro de templates da etiqueta?.
        /// </summary>
        internal static string DELETE_PRINT_TEMPLATE_QUESTION {
            get {
                return ResourceManager.GetString("DELETE_PRINT_TEMPLATE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletar o template da etiqueta.
        /// </summary>
        internal static string DELETE_PRINT_TEMPLATE_QUESTION_TITLE {
            get {
                return ResourceManager.GetString("DELETE_PRINT_TEMPLATE_QUESTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O template não pode estar vazio.
        /// </summary>
        internal static string FILEDS_VALIDATION_TEXT_1 {
            get {
                return ResourceManager.GetString("FILEDS_VALIDATION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do template deve ter mais de 5 caracteres.
        /// </summary>
        internal static string FILEDS_VALIDATION_TEXT_2 {
            get {
                return ResourceManager.GetString("FILEDS_VALIDATION_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do template deve ter mais de 5 caracteres.
        /// </summary>
        internal static string FILEDS_VALIDATION_TEXT_3 {
            get {
                return ResourceManager.GetString("FILEDS_VALIDATION_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário de layouts da etiqueta iniciado pelo usuário {0}..
        /// </summary>
        internal static string FORM_LOAD_TEXT_1 {
            get {
                return ResourceManager.GetString("FORM_LOAD_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout da etiqueta carregados.
        /// </summary>
        internal static string GET_EDIT_TEMPLATE_TEXT_1 {
            get {
                return ResourceManager.GetString("GET_EDIT_TEMPLATE_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro do layout da etiqueta {0} obtido para edição pelo usuário {1}..
        /// </summary>
        internal static string GET_PRINT_TEMPLATE_TEXT_1 {
            get {
                return ResourceManager.GetString("GET_PRINT_TEMPLATE_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo inserir no cadastro de templates da etiqueta?.
        /// </summary>
        internal static string INSERT_PRINT_TEMPLATE_QUESTION {
            get {
                return ResourceManager.GetString("INSERT_PRINT_TEMPLATE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir template de etiqueta.
        /// </summary>
        internal static string INSERT_PRINT_TEMPLATE_QUESTION_TITLE {
            get {
                return ResourceManager.GetString("INSERT_PRINT_TEMPLATE_QUESTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string SAVE_TEXT_1 {
            get {
                return ResourceManager.GetString("SAVE_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar.
        /// </summary>
        internal static string SAVE_TEXT_2 {
            get {
                return ResourceManager.GetString("SAVE_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo atualizar cadastro de templates da etiqueta?.
        /// </summary>
        internal static string UPDATE_PRINT_TEMPLATE_QUESTION {
            get {
                return ResourceManager.GetString("UPDATE_PRINT_TEMPLATE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar o template da etiqueta.
        /// </summary>
        internal static string UPDATE_PRINT_TEMPLATE_QUESTION_TITLE {
            get {
                return ResourceManager.GetString("UPDATE_PRINT_TEMPLATE_QUESTION_TITLE", resourceCulture);
            }
        }
    }
}
