//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.Camera.Resources.CameraDriver {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CameraDriverMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CameraDriverMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.Camera.Resources.CameraDriver.CameraDriverMessages", typeof(CameraDriverMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket criado, aguardando câmera client. IP: {0}, Porta: {1}.
        /// </summary>
        internal static string CAMERA_CLIENT_SERVER_AWAITING {
            get {
                return ResourceManager.GetString("CAMERA_CLIENT_SERVER_AWAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket para conexão de câmera client não criado. IP: {0}, Porta: {1}.
        /// </summary>
        internal static string CAMERA_CLIENT_SERVER_DOWN {
            get {
                return ResourceManager.GetString("CAMERA_CLIENT_SERVER_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectado à câmera. IP: {0}, Porta: {1}.
        /// </summary>
        internal static string CAMERA_SERVER_CONNECTED {
            get {
                return ResourceManager.GetString("CAMERA_SERVER_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câmera não conectada. IP: {0}, Porta: {1}.
        /// </summary>
        internal static string CAMERA_SERVER_NOT_CONNECTED {
            get {
                return ResourceManager.GetString("CAMERA_SERVER_NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao desserializar dados da etiqueta.
        /// </summary>
        internal static string DICTIONARY_BUILD_ERROR {
            get {
                return ResourceManager.GetString("DICTIONARY_BUILD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitura do socket cancelada devido ao timeout..
        /// </summary>
        internal static string EXECUTE_TEXT_1 {
            get {
                return ResourceManager.GetString("EXECUTE_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao receber dados..
        /// </summary>
        internal static string EXECUTE_TEXT_2 {
            get {
                return ResourceManager.GetString("EXECUTE_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitura inválida.
        /// </summary>
        internal static string LEITURA_INVALIDA {
            get {
                return ResourceManager.GetString("LEITURA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não lido.
        /// </summary>
        internal static string NAO_LIDO {
            get {
                return ResourceManager.GetString("NAO_LIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo.
        /// </summary>
        internal static string TO_CAMERA_DATA_MODEL_TEXT_1 {
            get {
                return ResourceManager.GetString("TO_CAMERA_DATA_MODEL_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionalidade.
        /// </summary>
        internal static string TO_CAMERA_DATA_MODEL_TEXT_2 {
            get {
                return ResourceManager.GetString("TO_CAMERA_DATA_MODEL_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linha.
        /// </summary>
        internal static string TO_CAMERA_DATA_MODEL_TEXT_3 {
            get {
                return ResourceManager.GetString("TO_CAMERA_DATA_MODEL_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Recebidos.
        /// </summary>
        internal static string TO_CAMERA_DATA_MODEL_TEXT_4 {
            get {
                return ResourceManager.GetString("TO_CAMERA_DATA_MODEL_TEXT_4", resourceCulture);
            }
        }
    }
}
