//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.Business.Resources.ProductionService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductionServiceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductionServiceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.Business.Resources.ProductionService.ProductionServiceMessages", typeof(ProductionServiceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item aprovado | {0}.
        /// </summary>
        internal static string APPROVAL_MESSAGE_BASE {
            get {
                return ResourceManager.GetString("APPROVAL_MESSAGE_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup automático não realizado - Erro.
        /// </summary>
        internal static string AUTO_BACKUP_ERROR_1 {
            get {
                return ResourceManager.GetString("AUTO_BACKUP_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup automático não realizado - Configurações de backup automático (SystemSettings.DatabaseManagementSettings) não definidas.
        /// </summary>
        internal static string AUTO_BACKUP_TEXT_1 {
            get {
                return ResourceManager.GetString("AUTO_BACKUP_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup automático desabilitado. Operação não realizada..
        /// </summary>
        internal static string AUTO_BACKUP_TEXT_2 {
            get {
                return ResourceManager.GetString("AUTO_BACKUP_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup automático não realizado - Intervalo desde último backup.
        /// </summary>
        internal static string AUTO_BACKUP_TEXT_3 {
            get {
                return ResourceManager.GetString("AUTO_BACKUP_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dia.
        /// </summary>
        internal static string AUTO_BACKUP_TEXT_4 {
            get {
                return ResourceManager.GetString("AUTO_BACKUP_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dias.
        /// </summary>
        internal static string AUTO_BACKUP_TEXT_5 {
            get {
                return ResourceManager.GetString("AUTO_BACKUP_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to é inferior ao configurado.
        /// </summary>
        internal static string AUTO_BACKUP_TEXT_6 {
            get {
                return ResourceManager.GetString("AUTO_BACKUP_TEXT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao realizar o backup automático da base de dados.
        /// </summary>
        internal static string BACKUP_ACTION_ERROR_1 {
            get {
                return ResourceManager.GetString("BACKUP_ACTION_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup automático realizado com sucesso em.
        /// </summary>
        internal static string BACKUP_ACTION_TEXT_1 {
            get {
                return ResourceManager.GetString("BACKUP_ACTION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode e datamatrix não conferem.
        /// </summary>
        internal static string BARCODE_DATAMATRIX_MISMATCH_ERROR {
            get {
                return ResourceManager.GetString("BARCODE_DATAMATRIX_MISMATCH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lote do datamatrix não confere com a produção.
        /// </summary>
        internal static string BATCH_MISMATCH_ERROR {
            get {
                return ResourceManager.GetString("BATCH_MISMATCH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÂMERA {0} - DADOS RECEBIDOS - {1}.
        /// </summary>
        internal static string CAMERA_GROUP_READ_MESSAGE {
            get {
                return ResourceManager.GetString("CAMERA_GROUP_READ_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÂMERA 1 - DADOS RECEBIDOS - {0}.
        /// </summary>
        internal static string CAMERA_READ_MESSAGE {
            get {
                return ResourceManager.GetString("CAMERA_READ_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao extrair dados.
        /// </summary>
        internal static string CREATE_FIFO_ENTRY_TEXT_1 {
            get {
                return ResourceManager.GetString("CREATE_FIFO_ENTRY_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao criar dicionário de etiquetas.
        /// </summary>
        internal static string CREATE_LABELS_DICTIONARY_ERROR {
            get {
                return ResourceManager.GetString("CREATE_LABELS_DICTIONARY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao criar ordem de produção.
        /// </summary>
        internal static string CREATE_PRODUCTION_ORDER_ERROR {
            get {
                return ResourceManager.GetString("CREATE_PRODUCTION_ORDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao criar itens de produção.
        /// </summary>
        internal static string CREATE_PRODUCTIONS_ERROR {
            get {
                return ResourceManager.GetString("CREATE_PRODUCTIONS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN13 da etiqueta não confere com o produto.
        /// </summary>
        internal static string EAN13_MISMATCH_ERROR {
            get {
                return ResourceManager.GetString("EAN13_MISMATCH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de barras não lido.
        /// </summary>
        internal static string EMPTY_BARCODE_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_BARCODE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datamatrix não lido.
        /// </summary>
        internal static string EMPTY_DATAMATRIX_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_DATAMATRIX_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao registrar defeito.
        /// </summary>
        internal static string ERROR_ASSIGN_REJECT_REASON {
            get {
                return ResourceManager.GetString("ERROR_ASSIGN_REJECT_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECAGEM DE REJEITO NO FIFO - {0}.
        /// </summary>
        internal static string EVALUATE_FIFO_ITEM_MESSAGE {
            get {
                return ResourceManager.GetString("EVALUATE_FIFO_ITEM_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início do método.
        /// </summary>
        internal static string EVALUETE_FIRST_FIFO_ITEM_TEXT_1 {
            get {
                return ResourceManager.GetString("EVALUETE_FIRST_FIFO_ITEM_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim do método.
        /// </summary>
        internal static string EVALUETE_FIRST_FIFO_ITEM_TEXT_10 {
            get {
                return ResourceManager.GetString("EVALUETE_FIRST_FIFO_ITEM_TEXT_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item extraído do.
        /// </summary>
        internal static string EVALUETE_FIRST_FIFO_ITEM_TEXT_2 {
            get {
                return ResourceManager.GetString("EVALUETE_FIRST_FIFO_ITEM_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item aprovado.
        /// </summary>
        internal static string EVALUETE_FIRST_FIFO_ITEM_TEXT_3 {
            get {
                return ResourceManager.GetString("EVALUETE_FIRST_FIFO_ITEM_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovado.
        /// </summary>
        internal static string EVALUETE_FIRST_FIFO_ITEM_TEXT_4 {
            get {
                return ResourceManager.GetString("EVALUETE_FIRST_FIFO_ITEM_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item rejeitado.
        /// </summary>
        internal static string EVALUETE_FIRST_FIFO_ITEM_TEXT_5 {
            get {
                return ResourceManager.GetString("EVALUETE_FIRST_FIFO_ITEM_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravado.
        /// </summary>
        internal static string EVALUETE_FIRST_FIFO_ITEM_TEXT_6 {
            get {
                return ResourceManager.GetString("EVALUETE_FIRST_FIFO_ITEM_TEXT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Leitura Câmera.
        /// </summary>
        internal static string EVALUETE_FIRST_FIFO_ITEM_TEXT_7 {
            get {
                return ResourceManager.GetString("EVALUETE_FIRST_FIFO_ITEM_TEXT_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejeitado.
        /// </summary>
        internal static string EVALUETE_FIRST_FIFO_ITEM_TEXT_8 {
            get {
                return ResourceManager.GetString("EVALUETE_FIRST_FIFO_ITEM_TEXT_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitura.
        /// </summary>
        internal static string EVALUETE_FIRST_FIFO_ITEM_TEXT_9 {
            get {
                return ResourceManager.GetString("EVALUETE_FIRST_FIFO_ITEM_TEXT_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de validade do datamatrix não confere com a produção.
        /// </summary>
        internal static string EXPIRATION_DATE_MISMATCH_ERROR {
            get {
                return ResourceManager.GetString("EXPIRATION_DATE_MISMATCH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método de Geração de Etiquetas não reconhecido.
        /// </summary>
        internal static string EXTRACT_PRINT_DATA_FROM_SEARCH_KEY_ERROR_1 {
            get {
                return ResourceManager.GetString("EXTRACT_PRINT_DATA_FROM_SEARCH_KEY_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APROVADA | {0}.
        /// </summary>
        internal static string FIFO_VALIDATION_BY_CAMERA_STATUS_TEXT_1 {
            get {
                return ResourceManager.GetString("FIFO_VALIDATION_BY_CAMERA_STATUS_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REJEITADA | {0}.
        /// </summary>
        internal static string FIFO_VALIDATION_BY_CAMERA_STATUS_TEXT_2 {
            get {
                return ResourceManager.GetString("FIFO_VALIDATION_BY_CAMERA_STATUS_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to etiqueta.
        /// </summary>
        internal static string FIFO_VALIDATION_BY_CAMERA_STATUS_TEXT_3 {
            get {
                return ResourceManager.GetString("FIFO_VALIDATION_BY_CAMERA_STATUS_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRIAÇÃO DE EPC - Início do Método.
        /// </summary>
        internal static string GENERATE_EPC_TEXT_1 {
            get {
                return ResourceManager.GetString("GENERATE_EPC_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRIAÇÃO DE EPC - Sequencial gerado.
        /// </summary>
        internal static string GENERATE_EPC_TEXT_2 {
            get {
                return ResourceManager.GetString("GENERATE_EPC_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRIAÇÃO DE EPC - Epc gerado.
        /// </summary>
        internal static string GENERATE_EPC_TEXT_3 {
            get {
                return ResourceManager.GetString("GENERATE_EPC_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim do Método.
        /// </summary>
        internal static string GENERATE_EPC_TEXT_4 {
            get {
                return ResourceManager.GetString("GENERATE_EPC_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há itens disponíveis para consumo para o item lido.
        /// </summary>
        internal static string GENERATE_LABEL_TEXT_1 {
            get {
                return ResourceManager.GetString("GENERATE_LABEL_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao checar sinais de alarmes.
        /// </summary>
        internal static string GENERIC_ALARM_ERROR {
            get {
                return ResourceManager.GetString("GENERIC_ALARM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de impressora não disponível, não foi possível gerar alarme para desconexão.
        /// </summary>
        internal static string GET_PRINTER_ALARM_AND_DOWNTIME_TYPES_TEXT_1 {
            get {
                return ResourceManager.GetString("GET_PRINTER_ALARM_AND_DOWNTIME_TYPES_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sublote do datamatrix não confere com a produção.
        /// </summary>
        internal static string IDENTIFIER_MISMATCH_ERROR {
            get {
                return ResourceManager.GetString("IDENTIFIER_MISMATCH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parada por {0} rejeitos consecutivos de.
        /// </summary>
        internal static string INCREMENT_RFID_CONSECUTIVE_REJECTS_TEXT_1 {
            get {
                return ResourceManager.GetString("INCREMENT_RFID_CONSECUTIVE_REJECTS_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialPrintBufferAsync - envio de buffer inicial para impressora.
        /// </summary>
        internal static string INITIAL_PRINT_BUFFER_TEXT_1 {
            get {
                return ResourceManager.GetString("INITIAL_PRINT_BUFFER_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to etiquetas.
        /// </summary>
        internal static string INITIAL_PRINT_BUFFER_TEXT_2 {
            get {
                return ResourceManager.GetString("INITIAL_PRINT_BUFFER_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de payload inválido: {0}.
        /// </summary>
        internal static string INVALID_PAYLOAD_TYPE {
            get {
                return ResourceManager.GetString("INVALID_PAYLOAD_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitor de Conferência | Serial: {0} | {1}.
        /// </summary>
        internal static string LABELER_VALIDATION_READER {
            get {
                return ResourceManager.GetString("LABELER_VALIDATION_READER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao conferir aplicação.
        /// </summary>
        internal static string LABELER_VALIDATION_READER_ERROR {
            get {
                return ResourceManager.GetString("LABELER_VALIDATION_READER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao carregar Ordem de Produção.
        /// </summary>
        internal static string LOAD_PRINT_LIST_FROM_PRODUCTION_ORDER_ID_ERROR_1 {
            get {
                return ResourceManager.GetString("LOAD_PRINT_LIST_FROM_PRODUCTION_ORDER_ID_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recebendo payload por socket....
        /// </summary>
        internal static string MULTIPLE_UNIQUE_LABELS_TEXT_1 {
            get {
                return ResourceManager.GetString("MULTIPLE_UNIQUE_LABELS_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload recebido com sucesso.
        /// </summary>
        internal static string MULTIPLE_UNIQUE_LABELS_TEXT_2 {
            get {
                return ResourceManager.GetString("MULTIPLE_UNIQUE_LABELS_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to etiquetas.
        /// </summary>
        internal static string MULTIPLE_UNIQUE_LABELS_TEXT_3 {
            get {
                return ResourceManager.GetString("MULTIPLE_UNIQUE_LABELS_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há itens a serem conferidos na lista.
        /// </summary>
        internal static string NO_AVAILABLE_ITEMS_MESSAGE {
            get {
                return ResourceManager.GetString("NO_AVAILABLE_ITEMS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câmera de Conferência: Nenhum item a conferir.
        /// </summary>
        internal static string NO_ITEM_TO_VALIDATE {
            get {
                return ResourceManager.GetString("NO_ITEM_TO_VALIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não lido.
        /// </summary>
        internal static string NO_READ {
            get {
                return ResourceManager.GetString("NO_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALARME: Caixa não lida | Célula {0} Linha {1}.
        /// </summary>
        internal static string NO_READ_ALARM_LOG_MESSAGE {
            get {
                return ResourceManager.GetString("NO_READ_ALARM_LOG_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de payload não informado.
        /// </summary>
        internal static string NULL_PAYLOAD_TYPE {
            get {
                return ResourceManager.GetString("NULL_PAYLOAD_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao gerar etiqueta.
        /// </summary>
        internal static string PAYLOAD_CONSUMPTION_ERROR_1 {
            get {
                return ResourceManager.GetString("PAYLOAD_CONSUMPTION_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câmera de Entrada - Nenhuma produção encontrada para o.
        /// </summary>
        internal static string PAYLOAD_CONSUMPTION_TEXT_1 {
            get {
                return ResourceManager.GetString("PAYLOAD_CONSUMPTION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrigindo erro na tb_production_info.
        /// </summary>
        internal static string PAYLOAD_CONSUMPTION_TEXT_2 {
            get {
                return ResourceManager.GetString("PAYLOAD_CONSUMPTION_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item não identificado.
        /// </summary>
        internal static string PAYLOAD_CONSUMPTION_TEXT_3 {
            get {
                return ResourceManager.GetString("PAYLOAD_CONSUMPTION_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitor de Validação - Contagem de pixels da etiqueta: O leitor não enviou nenhum valor correspondente.
        /// </summary>
        internal static string PIXEL_COUNT_CHECK_TEXT_1 {
            get {
                return ResourceManager.GetString("PIXEL_COUNT_CHECK_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitor de Validação - Contagem de pixels da etiqueta: O leitor não enviou os valores correspondentes.
        /// </summary>
        internal static string PIXEL_COUNT_CHECK_TEXT_2 {
            get {
                return ResourceManager.GetString("PIXEL_COUNT_CHECK_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string PROCESS_SELECTED_VALIDATION_READER_DATA_ERROR_1 {
            get {
                return ResourceManager.GetString("PROCESS_SELECTED_VALIDATION_READER_DATA_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum item na fila.
        /// </summary>
        internal static string PROCESS_SELECTED_VALIDATION_READER_DATA_TEXT_1 {
            get {
                return ResourceManager.GetString("PROCESS_SELECTED_VALIDATION_READER_DATA_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo do código de barras inválido.
        /// </summary>
        internal static string PROCESS_SELECTED_VALIDATION_READER_DATA_TEXT_2 {
            get {
                return ResourceManager.GetString("PROCESS_SELECTED_VALIDATION_READER_DATA_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O item esperado não contém.
        /// </summary>
        internal static string PROCESS_SELECTED_VALIDATION_READER_DATA_TEXT_3 {
            get {
                return ResourceManager.GetString("PROCESS_SELECTED_VALIDATION_READER_DATA_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análise de qualidade.
        /// </summary>
        internal static string PROCESS_SELECTED_VALIDATION_READER_DATA_TEXT_4 {
            get {
                return ResourceManager.GetString("PROCESS_SELECTED_VALIDATION_READER_DATA_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave de extração não lida.
        /// </summary>
        internal static string PROCESS_SELECTED_VALIDATION_READER_DATA_TEXT_5 {
            get {
                return ResourceManager.GetString("PROCESS_SELECTED_VALIDATION_READER_DATA_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de produção do datamatrix não confere com a produção.
        /// </summary>
        internal static string PRODUCTION_DATE_MISMATCH_ERROR {
            get {
                return ResourceManager.GetString("PRODUCTION_DATE_MISMATCH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produção não iniciada.
        /// </summary>
        internal static string RECEIVED_CAMERA_DATA_CAMERA_GROUP_TEXT_1 {
            get {
                return ResourceManager.GetString("RECEIVED_CAMERA_DATA_CAMERA_GROUP_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GERENCIANDO BUFFER DE RFID.
        /// </summary>
        internal static string RECORD_RFID_TEXT_1 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to é.
        /// </summary>
        internal static string RECORD_RFID_TEXT_10 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atualizado.
        /// </summary>
        internal static string RECORD_RFID_TEXT_11 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravado.
        /// </summary>
        internal static string RECORD_RFID_TEXT_12 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação de extração do buffer não executada: Buffer zerado.
        /// </summary>
        internal static string RECORD_RFID_TEXT_13 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início do Método.
        /// </summary>
        internal static string RECORD_RFID_TEXT_2 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removido do FIFO com sucesso.
        /// </summary>
        internal static string RECORD_RFID_TEXT_3 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na remoção do epc do fifo.
        /// </summary>
        internal static string RECORD_RFID_TEXT_4 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item extraído para gravação.
        /// </summary>
        internal static string RECORD_RFID_TEXT_5 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGUAL ao.
        /// </summary>
        internal static string RECORD_RFID_TEXT_6 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIFERENTE do.
        /// </summary>
        internal static string RECORD_RFID_TEXT_7 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitura do RFID - EPC a ser gravado.
        /// </summary>
        internal static string RECORD_RFID_TEXT_8 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lido após a gravação.
        /// </summary>
        internal static string RECORD_RFID_TEXT_9 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item rejeitado | {0}.
        /// </summary>
        internal static string REJECT_MESSAGE_BASE {
            get {
                return ResourceManager.GetString("REJECT_MESSAGE_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeito registrado | Serial: {0} | Motivo: {1}.
        /// </summary>
        internal static string REJECT_REASON_ASSIGNED {
            get {
                return ResourceManager.GetString("REJECT_REASON_ASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBSTITUIR VARIÁVEIS DE IMPRESSÃO - Início do Método.
        /// </summary>
        internal static string REPLACE_PRINT_VARIABLES_TEXT_1 {
            get {
                return ResourceManager.GetString("REPLACE_PRINT_VARIABLES_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBSTITUIR VARIÁVEIS DE IMPRESSÃO - Fim do método - Script gerado.
        /// </summary>
        internal static string REPLACE_PRINT_VARIABLES_TEXT_2 {
            get {
                return ResourceManager.GetString("REPLACE_PRINT_VARIABLES_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial não encontrado.
        /// </summary>
        internal static string SERIAL_NOT_FOUND {
            get {
                return ResourceManager.GetString("SERIAL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEITURA DO CLP - Sinal: &apos;{0}&apos; - Valor: &apos;{1}&apos;.
        /// </summary>
        internal static string SIGNAL_RECEIVED_MESSAGE {
            get {
                return ResourceManager.GetString("SIGNAL_RECEIVED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODO DE PRODUÇÃO INICIADO - Produto.
        /// </summary>
        internal static string START_PRODUCTION_MODE_TEXT_1 {
            get {
                return ResourceManager.GetString("START_PRODUCTION_MODE_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operador.
        /// </summary>
        internal static string START_PRODUCTION_MODE_TEXT_2 {
            get {
                return ResourceManager.GetString("START_PRODUCTION_MODE_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODO DE TESTE INICIADO.
        /// </summary>
        internal static string START_TEST_MODE_TEXT_1 {
            get {
                return ResourceManager.GetString("START_TEST_MODE_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo decorrido de ciclo: {0}.
        /// </summary>
        internal static string START_TEST_MODE_TEXT_2 {
            get {
                return ResourceManager.GetString("START_TEST_MODE_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODO DE TESTE INTERROMPIDO.
        /// </summary>
        internal static string START_TEST_MODE_TEXT_3 {
            get {
                return ResourceManager.GetString("START_TEST_MODE_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Ação do sistema: {1}.
        /// </summary>
        internal static string SYSTEM_ACTION_LOG {
            get {
                return ResourceManager.GetString("SYSTEM_ACTION_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Erro: {1}.
        /// </summary>
        internal static string SYSTEM_ERROR_LOG {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressora não conectada.
        /// </summary>
        internal static string TEST_INITIAL_PRINTER_CONNECTION_TEXT_1 {
            get {
                return ResourceManager.GetString("TEST_INITIAL_PRINTER_CONNECTION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não disponível.
        /// </summary>
        internal static string UNAVAILABLE_SERIAL {
            get {
                return ResourceManager.GetString("UNAVAILABLE_SERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro no processamento da leitura de conferência.
        /// </summary>
        internal static string VALIDATION_FRO_PRINT_LABELS_LIST_ERROR_1 {
            get {
                return ResourceManager.GetString("VALIDATION_FRO_PRINT_LABELS_LIST_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem de Produção.
        /// </summary>
        internal static string VALIDATION_FRO_PRINT_LABELS_LIST_TEXT_1 {
            get {
                return ResourceManager.GetString("VALIDATION_FRO_PRINT_LABELS_LIST_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to concluída. Finalizando....
        /// </summary>
        internal static string VALIDATION_FRO_PRINT_LABELS_LIST_TEXT_2 {
            get {
                return ResourceManager.GetString("VALIDATION_FRO_PRINT_LABELS_LIST_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finalizada automaticamente.
        /// </summary>
        internal static string VALIDATION_FRO_PRINT_LABELS_LIST_TEXT_3 {
            get {
                return ResourceManager.GetString("VALIDATION_FRO_PRINT_LABELS_LIST_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso [{0}kg] acima do máximo para o produto.
        /// </summary>
        internal static string WEIGHT_ABOVE_MAX_PRINT_MESSAGE {
            get {
                return ResourceManager.GetString("WEIGHT_ABOVE_MAX_PRINT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso [{0}kg] abaixo do mínimo para o produto.
        /// </summary>
        internal static string WEIGHT_BELOW_MIN_PRINT_MESSAGE {
            get {
                return ResourceManager.GetString("WEIGHT_BELOW_MIN_PRINT_MESSAGE", resourceCulture);
            }
        }
    }
}
