//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.App.Resources.FormMessages.frmSettingDatabase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class frmSettingDatabaseMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmSettingDatabaseMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.App.Resources.FormMessages.frmSettingDatabase.frmSettingDatabaseMe" +
                            "ssages", typeof(frmSettingDatabaseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Configurações Database | Ação: {1} | Erro: {2}.
        /// </summary>
        internal static string ACTION_ERROR_LOG {
            get {
                return ResourceManager.GetString("ACTION_ERROR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar criar o backup criptografado.
        /// </summary>
        internal static string BTN_CREATE_BACKUP_ERROR_1 {
            get {
                return ResourceManager.GetString("BTN_CREATE_BACKUP_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Backup Criptografado.
        /// </summary>
        internal static string BTN_CREATE_BACKUP_ERROR_2 {
            get {
                return ResourceManager.GetString("BTN_CREATE_BACKUP_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criando backup.
        /// </summary>
        internal static string BTN_CREATE_BACKUP_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_CREATE_BACKUP_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma pasta para salvar o backup criptografado.
        /// </summary>
        internal static string BTN_CREATE_BACKUP_TEXT_2 {
            get {
                return ResourceManager.GetString("BTN_CREATE_BACKUP_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Criar Backup Criptografado.
        /// </summary>
        internal static string BTN_CREATE_BACKUP_TEXT_3 {
            get {
                return ResourceManager.GetString("BTN_CREATE_BACKUP_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Excluir.
        /// </summary>
        internal static string BTN_DELETE_SETTINGS_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_DELETE_SETTINGS_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma pasta para salvar automaticamente o backup criptografado.
        /// </summary>
        internal static string BTN_DUMP_FOLDER_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_DUMP_FOLDER_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão para selecionar caminho de backup automático.
        /// </summary>
        internal static string BTN_DUMP_FOLDER_TEXT_2 {
            get {
                return ResourceManager.GetString("BTN_DUMP_FOLDER_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar restaurar o backup criptografado.
        /// </summary>
        internal static string BTN_RESTORE_DUMP_ERROR_1 {
            get {
                return ResourceManager.GetString("BTN_RESTORE_DUMP_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurando backup.
        /// </summary>
        internal static string BTN_RESTORE_DUMP_TEXT_3 {
            get {
                return ResourceManager.GetString("BTN_RESTORE_DUMP_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um arquivo para restaurar.
        /// </summary>
        internal static string BTN_RESTORE_DUMP_TEXT_4 {
            get {
                return ResourceManager.GetString("BTN_RESTORE_DUMP_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups encriptados (*.encrypted)|*.encrypted.
        /// </summary>
        internal static string BTN_RESTORE_DUMP_TEXT_5 {
            get {
                return ResourceManager.GetString("BTN_RESTORE_DUMP_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Restaurar Backup Criptografado.
        /// </summary>
        internal static string BTN_RESTORE_DUMP_TEXT_6 {
            get {
                return ResourceManager.GetString("BTN_RESTORE_DUMP_TEXT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar configurações de Backup Automático.
        /// </summary>
        internal static string BTN_SAVE_AUTO_DUMP_ERROR_1 {
            get {
                return ResourceManager.GetString("BTN_SAVE_AUTO_DUMP_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string BTN_SAVE_AUTO_DUMP_ERROR_2 {
            get {
                return ResourceManager.GetString("BTN_SAVE_AUTO_DUMP_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar configurações de backup automático: o valor.
        /// </summary>
        internal static string BTN_SAVE_AUTO_DUMP_ERROR_3 {
            get {
                return ResourceManager.GetString("BTN_SAVE_AUTO_DUMP_ERROR_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to definido como Intervalo de backup automático pelo usuário.
        /// </summary>
        internal static string BTN_SAVE_AUTO_DUMP_ERROR_4 {
            get {
                return ResourceManager.GetString("BTN_SAVE_AUTO_DUMP_ERROR_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to não é um número inteiro entre 0 e 90.
        /// </summary>
        internal static string BTN_SAVE_AUTO_DUMP_ERROR_5 {
            get {
                return ResourceManager.GetString("BTN_SAVE_AUTO_DUMP_ERROR_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O intervalo de backup deve ser um número inteiro,\r\nentre 1 e 90 (dias).
        /// </summary>
        internal static string BTN_SAVE_AUTO_DUMP_ERROR_6 {
            get {
                return ResourceManager.GetString("BTN_SAVE_AUTO_DUMP_ERROR_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor inválido.
        /// </summary>
        internal static string BTN_SAVE_AUTO_DUMP_ERROR_7 {
            get {
                return ResourceManager.GetString("BTN_SAVE_AUTO_DUMP_ERROR_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As alterações foram salvas com sucesso!\r\nPor favor, reinicie o software para que as mudanças tenham efeito..
        /// </summary>
        internal static string BTN_SAVE_AUTO_DUMP_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_SAVE_AUTO_DUMP_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Automático.
        /// </summary>
        internal static string BTN_SAVE_AUTO_DUMP_TEXT_2 {
            get {
                return ResourceManager.GetString("BTN_SAVE_AUTO_DUMP_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão &apos;Salvar Configurações&apos; da seção &apos;Backup Automático&apos;.
        /// </summary>
        internal static string BTN_SAVE_AUTO_DUMP_TEXT_3 {
            get {
                return ResourceManager.GetString("BTN_SAVE_AUTO_DUMP_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar configurações.
        /// </summary>
        internal static string BTN_SAVE_CONFIG_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_SAVE_CONFIG_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Salvar.
        /// </summary>
        internal static string BTN_SAVE_CONFIG_TEXT_2 {
            get {
                return ResourceManager.GetString("BTN_SAVE_CONFIG_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar testar a conexão com a base de dados..
        /// </summary>
        internal static string BTN_TEST_CONNECTION_ERROR_1 {
            get {
                return ResourceManager.GetString("BTN_TEST_CONNECTION_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testar conexão com a base de dados.
        /// </summary>
        internal static string BTN_TEST_CONNECTION_ERROR_2 {
            get {
                return ResourceManager.GetString("BTN_TEST_CONNECTION_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema ao tentar obter os dados de conexão com a base de dados.
        /// </summary>
        internal static string BTN_TEST_CONNECTION_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_TEST_CONNECTION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema ao tentar conectar com a base de dados.
        /// </summary>
        internal static string BTN_TEST_CONNECTION_TEXT_2 {
            get {
                return ResourceManager.GetString("BTN_TEST_CONNECTION_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexão com a base de dados realizada com sucesso!.
        /// </summary>
        internal static string BTN_TEST_CONNECTION_TEXT_3 {
            get {
                return ResourceManager.GetString("BTN_TEST_CONNECTION_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teste de conexão com a base de dados realizado com sucesso..
        /// </summary>
        internal static string BTN_TEST_CONNECTION_TEXT_4 {
            get {
                return ResourceManager.GetString("BTN_TEST_CONNECTION_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Testar Conexão.
        /// </summary>
        internal static string BTN_TEST_CONNECTION_TEXT_5 {
            get {
                return ResourceManager.GetString("BTN_TEST_CONNECTION_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desabilitado.
        /// </summary>
        internal static string CHK_AUTO_DUMP_STATUS_1 {
            get {
                return ResourceManager.GetString("CHK_AUTO_DUMP_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitado.
        /// </summary>
        internal static string CHK_AUTO_DUMP_STATUS_2 {
            get {
                return ResourceManager.GetString("CHK_AUTO_DUMP_STATUS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base de dados - Configurações.
        /// </summary>
        internal static string CONFIG_TITLE_1 {
            get {
                return ResourceManager.GetString("CONFIG_TITLE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurar Backup Criptografado.
        /// </summary>
        internal static string CONFIG_TITLE_2 {
            get {
                return ResourceManager.GetString("CONFIG_TITLE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criou Backup Criptografado no caminho.
        /// </summary>
        internal static string CREATE_BACKUP_PROCESS_TEXT_1 {
            get {
                return ResourceManager.GetString("CREATE_BACKUP_PROCESS_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja criar backup criptografado em {0}?.
        /// </summary>
        internal static string CREATE_ENCRYPTED_BACKUP_DIALOG_PROMPT {
            get {
                return ResourceManager.GetString("CREATE_ENCRYPTED_BACKUP_DIALOG_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar backup criptografado.
        /// </summary>
        internal static string CREATE_ENCRYPTED_BACKUP_DIALOG_TITLE {
            get {
                return ResourceManager.GetString("CREATE_ENCRYPTED_BACKUP_DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao exibir dados de dispositivos na tela de configuração..
        /// </summary>
        internal static string FORM_LOAD_ERROR_1 {
            get {
                return ResourceManager.GetString("FORM_LOAD_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de dispositivos carregados na tela de configuração..
        /// </summary>
        internal static string FORM_LOAD_TEXT_1 {
            get {
                return ResourceManager.GetString("FORM_LOAD_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurou Backup Criptografado do arquivo.
        /// </summary>
        internal static string IMPORT_BACKUP_PROCESS_TEXT_1 {
            get {
                return ResourceManager.GetString("IMPORT_BACKUP_PROCESS_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu nível de acesso [{0}] não possui autorização para realizar todas as ação deste formulário.
        /// </summary>
        internal static string MSGBOX_ACTION_LIMITED_ALLOWED {
            get {
                return ResourceManager.GetString("MSGBOX_ACTION_LIMITED_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu nível de acesso [{0}] não possui autorização para realizar essa ação.
        /// </summary>
        internal static string MSGBOX_ACTION_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("MSGBOX_ACTION_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar deletar os dados da base de dados!.
        /// </summary>
        internal static string MSGBOX_DELETE_DATA_ERROR_1 {
            get {
                return ResourceManager.GetString("MSGBOX_DELETE_DATA_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir dados por período.
        /// </summary>
        internal static string MSGBOX_DELETE_DATA_ERROR_2 {
            get {
                return ResourceManager.GetString("MSGBOX_DELETE_DATA_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar carregar os dados de configuração da base de dados!.
        /// </summary>
        internal static string MSGBOX_LOAD_DATA_ERROR {
            get {
                return ResourceManager.GetString("MSGBOX_LOAD_DATA_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar gravar os dados de configuração da base de dados!.
        /// </summary>
        internal static string MSGBOX_SAVE_DATA_ERROR {
            get {
                return ResourceManager.GetString("MSGBOX_SAVE_DATA_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível obter os dados de conexão com a base de dados.
        /// </summary>
        internal static string NETWORK_CONNCETION_ERROR_1 {
            get {
                return ResourceManager.GetString("NETWORK_CONNCETION_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao obter dados de conexão.
        /// </summary>
        internal static string NETWORK_CONNCETION_ERROR_2 {
            get {
                return ResourceManager.GetString("NETWORK_CONNCETION_ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurar backup criptografado.
        /// </summary>
        internal static string RESTORE_ENCRYPTED_BACKUP_DIALOG_TITLE {
            get {
                return ResourceManager.GetString("RESTORE_ENCRYPTED_BACKUP_DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As alterações foram salvas com sucesso!\r\nPor favor, reinicie o software para que as mudanças tenham efeito..
        /// </summary>
        internal static string SAVE_DEVICES_PROCESS_TEXT_1 {
            get {
                return ResourceManager.GetString("SAVE_DEVICES_PROCESS_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Configurações Database | Ação: {1}.
        /// </summary>
        internal static string USER_ACTION_LOG {
            get {
                return ResourceManager.GetString("USER_ACTION_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Configurações Database | Ação: Clicou em {1}.
        /// </summary>
        internal static string USER_CLICK_LOG {
            get {
                return ResourceManager.GetString("USER_CLICK_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Configurações Database - Backup Automático | Ação: Salvou configurações: {1}.
        /// </summary>
        internal static string USER_SAVED_SETTINGS_LOG {
            get {
                return ResourceManager.GetString("USER_SAVED_SETTINGS_LOG", resourceCulture);
            }
        }
    }
}
