//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.Plc.Resources.PlcExternalService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlcExternalServiceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlcExternalServiceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.Plc.Resources.PlcExternalService.PlcExternalServiceMessages", typeof(PlcExternalServiceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receita enviada: Velocidade {0}, Tamanho {1}, Atraso {2}, Rampa Acel {3}, Rampa Desac {4}, Filtro {5}.
        /// </summary>
        internal static string APPLICATOR_PRESET_LOG {
            get {
                return ResourceManager.GetString("APPLICATOR_PRESET_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life bit.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_1 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor OUT - cilindro.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_10 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicador em emergência.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_11 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na impressora.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_12 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liner rompido.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_13 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor IN fora de posição.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_14 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor OUT fora de posição.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_15 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falta de Etiqueta.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_16 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botão de emergência acionado.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_17 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porta aberta.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_2 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máquina operando.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_3 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipamento sem ar comprimido.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_4 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acúmulo no rejeito.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_5 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Accumulation.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_6 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor de aplicação.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_7 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor do rebobinador.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_8 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor IN - cilindro.
        /// </summary>
        internal static string BOOL_VARIABLES_TEXT_9 {
            get {
                return ResourceManager.GetString("BOOL_VARIABLES_TEXT_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidade Aplicador.
        /// </summary>
        internal static string INPUT_REGISTERS_TEXT_1 {
            get {
                return ResourceManager.GetString("INPUT_REGISTERS_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atraso de Aplicação.
        /// </summary>
        internal static string INPUT_REGISTERS_TEXT_2 {
            get {
                return ResourceManager.GetString("INPUT_REGISTERS_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atraso de Rejeito.
        /// </summary>
        internal static string INPUT_REGISTERS_TEXT_3 {
            get {
                return ResourceManager.GetString("INPUT_REGISTERS_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLP Conectado.
        /// </summary>
        internal static string PLC_CONNECTED_LOG {
            get {
                return ResourceManager.GetString("PLC_CONNECTED_LOG", resourceCulture);
            }
        }
    }
}
