//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.App.Resources.FormMessages.frmSettingWSAuroraToledo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class frmSettingWSAuroraToledoMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmSettingWSAuroraToledoMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.App.Resources.FormMessages.frmSettingWSAuroraToledo.frmSettingWSAu" +
                            "roraToledoMessages", typeof(frmSettingWSAuroraToledoMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao conectar-se ao WS Aurora.\nVerifique a conexão e tente novamente..
        /// </summary>
        internal static string AURORA_CONNECTION_ERROR {
            get {
                return ResourceManager.GetString("AURORA_CONNECTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS Aurora - Status da Conexão.
        /// </summary>
        internal static string AURORA_CONNECTION_ERROR_TITLE {
            get {
                return ResourceManager.GetString("AURORA_CONNECTION_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Salvar - WS Aurora.
        /// </summary>
        internal static string BTN_AURORA_SAVE_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_AURORA_SAVE_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Testar conexão - WS Toledo.
        /// </summary>
        internal static string BTN_TOLEDO_SAVE_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_TOLEDO_SAVE_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Testar conexão - WS Aurora.
        /// </summary>
        internal static string BTN_WS_AURORA_TEST_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_WS_AURORA_TEST_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Testar conexão - WS Toledo.
        /// </summary>
        internal static string BTN_WS_TOLEDO_TEST_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_WS_TOLEDO_TEST_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS Toledo - Configurações.
        /// </summary>
        internal static string CONFIG_TITLE_1 {
            get {
                return ResourceManager.GetString("CONFIG_TITLE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS Aurora - Configurações.
        /// </summary>
        internal static string CONFIG_TITLE_2 {
            get {
                return ResourceManager.GetString("CONFIG_TITLE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao exibir dados do WS na tela de configuração..
        /// </summary>
        internal static string FORM_LOAD_ERROR_1 {
            get {
                return ResourceManager.GetString("FORM_LOAD_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do WS carregados na tela de configuração..
        /// </summary>
        internal static string FORM_LOAD_TEXT_1 {
            get {
                return ResourceManager.GetString("FORM_LOAD_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string MSG_ERROR_TEXT_1 {
            get {
                return ResourceManager.GetString("MSG_ERROR_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu nível de acesso [{0}] não possui autorização para realizar todas as ação deste formulário.
        /// </summary>
        internal static string MSGBOX_ACTION_LIMITED_ALLOWED {
            get {
                return ResourceManager.GetString("MSGBOX_ACTION_LIMITED_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu nível de acesso [{0}] não possui autorização para realizar essa ação.
        /// </summary>
        internal static string MSGBOX_ACTION_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("MSGBOX_ACTION_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações salvas com sucesso!.
        /// </summary>
        internal static string SAVE_PROCESS_TEXT_1 {
            get {
                return ResourceManager.GetString("SAVE_PROCESS_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao conectar-se ao WS Toledo.\nVerifique a conexão e tente novamente..
        /// </summary>
        internal static string TOLEDO_CONNECTION_ERROR {
            get {
                return ResourceManager.GetString("TOLEDO_CONNECTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS Toledo - Status da Conexão.
        /// </summary>
        internal static string TOLEDO_CONNECTION_ERROR_TITLE {
            get {
                return ResourceManager.GetString("TOLEDO_CONNECTION_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela Web Services - Usuário {0} clicou {1}.
        /// </summary>
        internal static string USER_CLICK_LOG {
            get {
                return ResourceManager.GetString("USER_CLICK_LOG", resourceCulture);
            }
        }
    }
}
