//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.App.Resources.FormMessages.FrmRejectReasonEntries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrmRejectReasonEntriesMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrmRejectReasonEntriesMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.App.Resources.FormMessages.FrmRejectReasonEntries.FrmRejectReasonE" +
                            "ntriesMessages", typeof(FrmRejectReasonEntriesMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Aba Cadastro de Motivos de Rejeito | Ação: {1} | Erro: {2}.
        /// </summary>
        internal static string ACTION_ERROR_LOG {
            get {
                return ResourceManager.GetString("ACTION_ERROR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vincular DataSource da lista de motivos de rejeito.
        /// </summary>
        internal static string DATABINDING_MESSAGE {
            get {
                return ResourceManager.GetString("DATABINDING_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar motivo de rejeito. Objeto:\r\n&apos;{0}.
        /// </summary>
        internal static string EDIT_REJECT_REASON {
            get {
                return ResourceManager.GetString("EDIT_REJECT_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela carregada.
        /// </summary>
        internal static string FORM_LOADED {
            get {
                return ResourceManager.GetString("FORM_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregar tela.
        /// </summary>
        internal static string LOAD_FORM {
            get {
                return ResourceManager.GetString("LOAD_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregar tela de Cadastro de Motivos de Rejeito.
        /// </summary>
        internal static string LOAD_FRM_REJECT_REASON_REGISTER {
            get {
                return ResourceManager.GetString("LOAD_FRM_REJECT_REASON_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregar lista de motivos de rejeito.
        /// </summary>
        internal static string LOAD_REJECT_REASON_LIST {
            get {
                return ResourceManager.GetString("LOAD_REJECT_REASON_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando tela.
        /// </summary>
        internal static string LOADING_FORM {
            get {
                return ResourceManager.GetString("LOADING_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Novo.
        /// </summary>
        internal static string NEW_REGISTER {
            get {
                return ResourceManager.GetString("NEW_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Aba Cadastro de Motivos de Rejeito | Ação: {1}.
        /// </summary>
        internal static string USER_ACTION_LOG {
            get {
                return ResourceManager.GetString("USER_ACTION_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Aba Cadastro de Motivos de Rejeito | Clicou em: {1}.
        /// </summary>
        internal static string USER_CLICK_LOG {
            get {
                return ResourceManager.GetString("USER_CLICK_LOG", resourceCulture);
            }
        }
    }
}
