//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.App.Resources.FormMessages.FrmRejectReasonRegister {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrmRejectReasonRegisterMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrmRejectReasonRegisterMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.App.Resources.FormMessages.FrmRejectReasonRegister.FrmRejectReason" +
                            "RegisterMessages", typeof(FrmRejectReasonRegisterMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Cadastro - Motivo de Rejeito | Ação: {1} | Erro: {2}.
        /// </summary>
        internal static string ACTION_ERROR_LOG {
            get {
                return ResourceManager.GetString("ACTION_ERROR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha NOME e DESCRIÇÃO de pelo menos um idioma.
        /// </summary>
        internal static string ALL_FIELDS_EMPTY_PLC_VARIABLE {
            get {
                return ResourceManager.GetString("ALL_FIELDS_EMPTY_PLC_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um motivo de rejeito habilitado vinculado à entrada {0}\r\nPara utilizar esta entrada, desabilite o outro motivo de rejeito que possua este vínculo..
        /// </summary>
        internal static string ALREADY_ASSIGNED_PLC_VARIABLE {
            get {
                return ResourceManager.GetString("ALREADY_ASSIGNED_PLC_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar entrada vinculada.
        /// </summary>
        internal static string CHANGE_BINDED_VARIABLE {
            get {
                return ResourceManager.GetString("CHANGE_BINDED_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterou campo descrição: &apos;{0}&apos;.
        /// </summary>
        internal static string CHANGE_DESCRIPTION_FIELD {
            get {
                return ResourceManager.GetString("CHANGE_DESCRIPTION_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar idioma para edição.
        /// </summary>
        internal static string CHANGE_EDIT_LANGUAGE {
            get {
                return ResourceManager.GetString("CHANGE_EDIT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterou campo nome: &apos;{0}&apos;.
        /// </summary>
        internal static string CHANGE_NAME_FIELD {
            get {
                return ResourceManager.GetString("CHANGE_NAME_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar tela.
        /// </summary>
        internal static string CLOSE_FORM {
            get {
                return ResourceManager.GetString("CLOSE_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar novo registro.
        /// </summary>
        internal static string CREATE_REGISTER {
            get {
                return ResourceManager.GetString("CREATE_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar | {0}:\r\n{1}.
        /// </summary>
        internal static string CREATE_UPDATE_BASE_MESSAGE {
            get {
                return ResourceManager.GetString("CREATE_UPDATE_BASE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INATIVO.
        /// </summary>
        internal static string DISABLED_CONST {
            get {
                return ResourceManager.GetString("DISABLED_CONST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir teclado virtual.
        /// </summary>
        internal static string DISPLAY_ONSCREEN_KEYBOARD {
            get {
                return ResourceManager.GetString("DISPLAY_ONSCREEN_KEYBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATIVO.
        /// </summary>
        internal static string ENABLED_CONST {
            get {
                return ResourceManager.GetString("ENABLED_CONST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao salvar registro.
        /// </summary>
        internal static string FAIL_SAVE_MESSAGE {
            get {
                return ResourceManager.GetString("FAIL_SAVE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela carregada.
        /// </summary>
        internal static string FORM_LOADED {
            get {
                return ResourceManager.GetString("FORM_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregar dados nos controles de tela.
        /// </summary>
        internal static string LOAD_CONTROLS {
            get {
                return ResourceManager.GetString("LOAD_CONTROLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregar tela.
        /// </summary>
        internal static string LOAD_FORM {
            get {
                return ResourceManager.GetString("LOAD_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando tela.
        /// </summary>
        internal static string LOADING_FORM {
            get {
                return ResourceManager.GetString("LOADING_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregar lista no combobox de seleção de idioma.
        /// </summary>
        internal static string POPULATE_LANGUAGE_COMBOBOX {
            get {
                return ResourceManager.GetString("POPULATE_LANGUAGE_COMBOBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregar lista no combobox de seleção de entrada vinculada.
        /// </summary>
        internal static string POPULATE_VARIABLE_COMBOBOX {
            get {
                return ResourceManager.GetString("POPULATE_VARIABLE_COMBOBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar registro.
        /// </summary>
        internal static string SAVE_MESSAGE_TITLE {
            get {
                return ResourceManager.GetString("SAVE_MESSAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterou entrada vinculada: &apos;{0}&apos;.
        /// </summary>
        internal static string SELECTED_BINDED_VARIABLE {
            get {
                return ResourceManager.GetString("SELECTED_BINDED_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterado idioma para edição: &apos;{0}&apos; - &apos;{1}&apos;.
        /// </summary>
        internal static string SELECTED_EDIT_LANGUAGE {
            get {
                return ResourceManager.GetString("SELECTED_EDIT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro salvo com sucesso.
        /// </summary>
        internal static string SUCCESSFUL_SAVE_MESSAGE {
            get {
                return ResourceManager.GetString("SUCCESSFUL_SAVE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Status Habilitado: {0}.
        /// </summary>
        internal static string TOGGLE_ENABLED {
            get {
                return ResourceManager.GetString("TOGGLE_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar dicionário de descrição da entidade em memória.
        /// </summary>
        internal static string UPDATE_ENTITY_DESCRIPTION {
            get {
                return ResourceManager.GetString("UPDATE_ENTITY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar dicionário de nome da entidade em memória.
        /// </summary>
        internal static string UPDATE_ENTITY_NAME {
            get {
                return ResourceManager.GetString("UPDATE_ENTITY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro atualizado.
        /// </summary>
        internal static string UPDATE_REGISTER {
            get {
                return ResourceManager.GetString("UPDATE_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Cadastro - Motivo de Rejeito | Ação: {1}.
        /// </summary>
        internal static string USER_ACTION_LOG {
            get {
                return ResourceManager.GetString("USER_ACTION_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Cadastro - Motivo de Rejeito | Ação: Clicou {1}.
        /// </summary>
        internal static string USER_CLICK_LOG {
            get {
                return ResourceManager.GetString("USER_CLICK_LOG", resourceCulture);
            }
        }
    }
}
