//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.App.Resources.FormMessages.FrmProduction {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrmProductionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrmProductionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.App.Resources.FormMessages.FrmProduction.FrmProductionMessages", typeof(FrmProductionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Produção | Ação: {1} | Erro: {2}.
        /// </summary>
        internal static string ACTION_ERROR_LOG {
            get {
                return ResourceManager.GetString("ACTION_ERROR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máquina Pronta.
        /// </summary>
        internal static string ALARMS_LIST_UPDATE_HANDLER_TEXT_1 {
            get {
                return ResourceManager.GetString("ALARMS_LIST_UPDATE_HANDLER_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovado.
        /// </summary>
        internal static string APPROVED_MESSAGE {
            get {
                return ResourceManager.GetString("APPROVED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando início da produção.
        /// </summary>
        internal static string AWAITING_PRODUCTION_START_MESSAGE {
            get {
                return ResourceManager.GetString("AWAITING_PRODUCTION_START_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão para selecionar o lote.
        /// </summary>
        internal static string BATCH_CODE_TEXT_1 {
            get {
                return ResourceManager.GetString("BATCH_CODE_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automático.
        /// </summary>
        internal static string BTN_AUTOMATIC_MODE_AUTOMATIC {
            get {
                return ResourceManager.GetString("BTN_AUTOMATIC_MODE_AUTOMATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string BTN_AUTOMATIC_MODE_MANUAL {
            get {
                return ResourceManager.GetString("BTN_AUTOMATIC_MODE_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limpar os buffers.
        /// </summary>
        internal static string BTN_CLEAR_ERROR {
            get {
                return ResourceManager.GetString("BTN_CLEAR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão LIMPAR.
        /// </summary>
        internal static string BTN_CLEAR_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_CLEAR_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar.
        /// </summary>
        internal static string BTN_START_CAPTION_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_START_CAPTION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iniciar/parar a produção.
        /// </summary>
        internal static string BTN_START_ERROR {
            get {
                return ResourceManager.GetString("BTN_START_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produção iniciada.
        /// </summary>
        internal static string BTN_START_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão Iniciar/Parar.
        /// </summary>
        internal static string BTN_START_TEXT_2 {
            get {
                return ResourceManager.GetString("BTN_START_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela Produção carregada.
        /// </summary>
        internal static string CONSTRUCTOR_LOG_TEXT {
            get {
                return ResourceManager.GetString("CONSTRUCTOR_LOG_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading da tela de Produção.
        /// </summary>
        internal static string FORM_LOAD_TEXT_1 {
            get {
                return ResourceManager.GetString("FORM_LOAD_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Máquina.
        /// </summary>
        internal static string LABELED_PANEL_MACHINE_STATUS {
            get {
                return ResourceManager.GetString("LABELED_PANEL_MACHINE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Produção.
        /// </summary>
        internal static string LABELED_PANEL_PRODUCTION_STATUS {
            get {
                return ResourceManager.GetString("LABELED_PANEL_PRODUCTION_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para iniciar, altere o modo de produção para Automático na IHM.
        /// </summary>
        internal static string MANUAL_MODE_LOCK_MESSAGE {
            get {
                return ResourceManager.GetString("MANUAL_MODE_LOCK_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produção bloqueada.
        /// </summary>
        internal static string MANUAL_MODE_LOCK_TITLE {
            get {
                return ResourceManager.GetString("MANUAL_MODE_LOCK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação não permitida.
        /// </summary>
        internal static string MSGBOX_ACTION_NOT_ALLOWED_TITLE {
            get {
                return ResourceManager.GetString("MSGBOX_ACTION_NOT_ALLOWED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câmera Identificação.
        /// </summary>
        internal static string MULTI_LABEL_CAMERA_IDENTIFICATION_TEXT_1 {
            get {
                return ResourceManager.GetString("MULTI_LABEL_CAMERA_IDENTIFICATION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câmera Superior.
        /// </summary>
        internal static string MULTI_LABEL_CAMERA_IDENTIFICATION_TEXT_2 {
            get {
                return ResourceManager.GetString("MULTI_LABEL_CAMERA_IDENTIFICATION_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câmera Lateral.
        /// </summary>
        internal static string MULTI_LABEL_CAMERA_IDENTIFICATION_TEXT_3 {
            get {
                return ResourceManager.GetString("MULTI_LABEL_CAMERA_IDENTIFICATION_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para iniciar, selecione Produto.
        /// </summary>
        internal static string NO_SELECTED_PARAMETERS_MESSAGE {
            get {
                return ResourceManager.GetString("NO_SELECTED_PARAMETERS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum parâmetro selecionado.
        /// </summary>
        internal static string NO_SELECTED_PARAMETERS_TITLE {
            get {
                return ResourceManager.GetString("NO_SELECTED_PARAMETERS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressora não conectada. Para iniciar, verifique conexão..
        /// </summary>
        internal static string PRINTER_NOT_CONNECTED_MESSAGE {
            get {
                return ResourceManager.GetString("PRINTER_NOT_CONNECTED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressora não conectada.
        /// </summary>
        internal static string PRINTER_NOT_CONNECTED_TITLE {
            get {
                return ResourceManager.GetString("PRINTER_NOT_CONNECTED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejeitado - Sem leitura.
        /// </summary>
        internal static string REJECTED_NO_READ_MESSAGE {
            get {
                return ResourceManager.GetString("REJECTED_NO_READ_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão para selecionar o produto.
        /// </summary>
        internal static string SEARCH_PRODUCT_TEXT_1 {
            get {
                return ResourceManager.GetString("SEARCH_PRODUCT_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no botão para selecionar a ordem de produção.
        /// </summary>
        internal static string SEARCH_PRODUCTION_ORDER_TEXT_1 {
            get {
                return ResourceManager.GetString("SEARCH_PRODUCTION_ORDER_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string SYNC_DATA_ERROR {
            get {
                return ResourceManager.GetString("SYNC_DATA_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados sincronizados com sucesso.
        /// </summary>
        internal static string SYNC_DATE_TEXT_1 {
            get {
                return ResourceManager.GetString("SYNC_DATE_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronização concluída.
        /// </summary>
        internal static string SYNC_DATE_TEXT_2 {
            get {
                return ResourceManager.GetString("SYNC_DATE_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela Produção | Verificação de Produto: {0} | Status: Aprovado.
        /// </summary>
        internal static string SYSTEM_VERIFICATION_LOG_APPROVED {
            get {
                return ResourceManager.GetString("SYSTEM_VERIFICATION_LOG_APPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela Produção | Verificação de Produto: {0} | Status: Rejeitado.
        /// </summary>
        internal static string SYSTEM_VERIFICATION_LOG_REJECTED {
            get {
                return ResourceManager.GetString("SYSTEM_VERIFICATION_LOG_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar estado do botão Iniciar.
        /// </summary>
        internal static string TOGGLER_BTN_START_ERROR {
            get {
                return ResourceManager.GetString("TOGGLER_BTN_START_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterou estado do botão Iniciar para.
        /// </summary>
        internal static string TOGGLER_BTN_START_TEXT_1 {
            get {
                return ResourceManager.GetString("TOGGLER_BTN_START_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câmera Validação.
        /// </summary>
        internal static string TRIPLE_LABEL_CAMERA_VALIDATION_TEXT_1 {
            get {
                return ResourceManager.GetString("TRIPLE_LABEL_CAMERA_VALIDATION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produção.
        /// </summary>
        internal static string TRIPLE_LABEL_PRODUCTION_TEXT_1 {
            get {
                return ResourceManager.GetString("TRIPLE_LABEL_PRODUCTION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itens.
        /// </summary>
        internal static string TRIPLE_LABEL_PRODUCTION_TEXT_2 {
            get {
                return ResourceManager.GetString("TRIPLE_LABEL_PRODUCTION_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidade.
        /// </summary>
        internal static string TRIPLE_LABEL_SPEED_TEXT_1 {
            get {
                return ResourceManager.GetString("TRIPLE_LABEL_SPEED_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itens por minuto.
        /// </summary>
        internal static string TRIPLE_LABEL_SPEED_TEXT_2 {
            get {
                return ResourceManager.GetString("TRIPLE_LABEL_SPEED_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Produção | Ação: {1}.
        /// </summary>
        internal static string USER_ACTION_LOG {
            get {
                return ResourceManager.GetString("USER_ACTION_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Produção | Ação: Clicou {1}.
        /// </summary>
        internal static string USER_CLICK_LOG {
            get {
                return ResourceManager.GetString("USER_CLICK_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário {0} não possui nível de acesso para INICIAR/PARAR a produção. Usuário não autorizado..
        /// </summary>
        internal static string USER_CLICK_REGISTERS_LOG_PRODUCTION_STARTED_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("USER_CLICK_REGISTERS_LOG_PRODUCTION_STARTED_NOT_ALLOWED", resourceCulture);
            }
        }
    }
}
