//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.App.Resources.FormMessages.FrmItemCheck {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrmItemCheckMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrmItemCheckMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.App.Resources.FormMessages.FrmItemCheck.FrmItemCheckMessages", typeof(FrmItemCheckMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há itens pendentes. Obrigatório adicionar observações..
        /// </summary>
        internal static string FINISH_PRODUCTION_TEXT_1 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há itens pendentes. Deseja finalizar a ordem com as observações inseridas?.
        /// </summary>
        internal static string FINISH_PRODUCTION_TEXT_2 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem de produção vazia. Deseja finalizar?.
        /// </summary>
        internal static string FINISH_PRODUCTION_TEXT_3 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem de produção finalizada. Não há etiquetas vinculadas.
        /// </summary>
        internal static string FINISH_PRODUCTION_TEXT_4 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem de produção finalizada com sucesso.
        /// </summary>
        internal static string FINISH_PRODUCTION_TEXT_5 {
            get {
                return ResourceManager.GetString("FINISH_PRODUCTION_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando Lista.
        /// </summary>
        internal static string LOADING_PRODUCTION_ORDERS_TEXT_1 {
            get {
                return ResourceManager.GetString("LOADING_PRODUCTION_ORDERS_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos os itens conferidos, a ordem de produção será finalizada automaticamente..
        /// </summary>
        internal static string PRODUCTION_ORDER_FINALIZED_AUTOMATIC_TEXT_1 {
            get {
                return ResourceManager.GetString("PRODUCTION_ORDER_FINALIZED_AUTOMATIC_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar Ordem de Produção.
        /// </summary>
        internal static string PRODUCTION_ORDER_FINALIZED_AUTOMATIC_TITLE {
            get {
                return ResourceManager.GetString("PRODUCTION_ORDER_FINALIZED_AUTOMATIC_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O comentário deve ter, no máximo, 300 caracteres.
        /// </summary>
        internal static string TEXT_VALIDATION_1 {
            get {
                return ResourceManager.GetString("TEXT_VALIDATION_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho Excedido.
        /// </summary>
        internal static string TEXT_VALIDATION_TITLE {
            get {
                return ResourceManager.GetString("TEXT_VALIDATION_TITLE", resourceCulture);
            }
        }
    }
}
