//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.RfidDevice.Resources.RfidExternalService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RfidExternalServiceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RfidExternalServiceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.RfidDevice.Resources.RfidExternalService.RfidExternalServiceMessag" +
                            "es", typeof(RfidExternalServiceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao efetuar lock da tag!.
        /// </summary>
        internal static string FAIL_LOCK_MESSAGE {
            get {
                return ResourceManager.GetString("FAIL_LOCK_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na gravação da tag!.
        /// </summary>
        internal static string FAIL_RECORD_MESSAGE {
            get {
                return ResourceManager.GetString("FAIL_RECORD_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCK RFID  - Início do método de Lock do RFID.
        /// </summary>
        internal static string LOCK_RFID_TEXT_1 {
            get {
                return ResourceManager.GetString("LOCK_RFID_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCK RFID  - Final do método de Lock do RFID.
        /// </summary>
        internal static string LOCK_RFID_TEXT_2 {
            get {
                return ResourceManager.GetString("LOCK_RFID_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCK RFID  - Dispositivo desconectado.
        /// </summary>
        internal static string LOCK_RFID_TEXT_3 {
            get {
                return ResourceManager.GetString("LOCK_RFID_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início do método.
        /// </summary>
        internal static string PING_DEVICE_TEXT_1 {
            get {
                return ResourceManager.GetString("PING_DEVICE_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final do método - Status Connection.
        /// </summary>
        internal static string PING_DEVICE_TEXT_2 {
            get {
                return ResourceManager.GetString("PING_DEVICE_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LER RFID  - Início do método de leitura.
        /// </summary>
        internal static string READ_RFID_TEXT_1 {
            get {
                return ResourceManager.GetString("READ_RFID_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LER RFID - 3 tentativas sem sucesso.
        /// </summary>
        internal static string READ_RFID_TEXT_2 {
            get {
                return ResourceManager.GetString("READ_RFID_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LER RFID  - EPC Lido:.
        /// </summary>
        internal static string READ_RFID_TEXT_3 {
            get {
                return ResourceManager.GetString("READ_RFID_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LER RFID  - Timeout.
        /// </summary>
        internal static string READ_RFID_TEXT_4 {
            get {
                return ResourceManager.GetString("READ_RFID_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LER RFID  - Final do método de leitura.
        /// </summary>
        internal static string READ_RFID_TEXT_5 {
            get {
                return ResourceManager.GetString("READ_RFID_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LER RFID  - Erro na leitura: dispositivo RFID desconectado.
        /// </summary>
        internal static string READ_RFID_TEXT_6 {
            get {
                return ResourceManager.GetString("READ_RFID_TEXT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAVAR RFID  - Erro na gravação:.
        /// </summary>
        internal static string RECORD_RFID_ERROR_1 {
            get {
                return ResourceManager.GetString("RECORD_RFID_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAVAR RFID  - Início do método de gravação.
        /// </summary>
        internal static string RECORD_RFID_TEXT_1 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAVAR RFID  - Erro na gravação: dispositivo RFID desconectado.
        /// </summary>
        internal static string RECORD_RFID_TEXT_10 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAVAR RFID  - Erro na gravação : Tempo excedido | EPC:.
        /// </summary>
        internal static string RECORD_RFID_TEXT_11 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAVAR RFID  - O dispositivo RFID não respondeu.
        /// </summary>
        internal static string RECORD_RFID_TEXT_2 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentativa.
        /// </summary>
        internal static string RECORD_RFID_TEXT_3 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAVAR RFID  - Tentativa.
        /// </summary>
        internal static string RECORD_RFID_TEXT_4 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de gravação do EPC.
        /// </summary>
        internal static string RECORD_RFID_TEXT_5 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to falhou.
        /// </summary>
        internal static string RECORD_RFID_TEXT_6 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAVAR RFID  - Gravação do EPC.
        /// </summary>
        internal static string RECORD_RFID_TEXT_7 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to falhou - Timeout.
        /// </summary>
        internal static string RECORD_RFID_TEXT_8 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAVAR RFID  - Final do método de gravação | EPC:.
        /// </summary>
        internal static string RECORD_RFID_TEXT_9 {
            get {
                return ResourceManager.GetString("RECORD_RFID_TEXT_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFINIR POTÊNCIA DE {0} RFID.
        /// </summary>
        internal static string SET_RFID_POWER_MESSAGE {
            get {
                return ResourceManager.GetString("SET_RFID_POWER_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFINIR POTÊNCIA DE LEITURA RFID - Início do método.
        /// </summary>
        internal static string SET_RFID_POWER_TEXT_1 {
            get {
                return ResourceManager.GetString("SET_RFID_POWER_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFINIR POTÊNCIA DE LEITURA RFID  - Potência definida:.
        /// </summary>
        internal static string SET_RFID_POWER_TEXT_2 {
            get {
                return ResourceManager.GetString("SET_RFID_POWER_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFINIR POTÊNCIA DE LEITURA RFID  - Erro: dispositivo RFID desconectado.
        /// </summary>
        internal static string SET_RFID_POWER_TEXT_3 {
            get {
                return ResourceManager.GetString("SET_RFID_POWER_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock da tag efetuado com sucesso!.
        /// </summary>
        internal static string SUCCESS_LOCK_MESSAGE {
            get {
                return ResourceManager.GetString("SUCCESS_LOCK_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAVAR RFID  - Gravação efetuada com sucesso | EPC: {0}.
        /// </summary>
        internal static string SUCCESS_RECORD_MESSAGE {
            get {
                return ResourceManager.GetString("SUCCESS_RECORD_MESSAGE", resourceCulture);
            }
        }
    }
}
