//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplipack.TagID.App.Resources.FormMessages.FrmUser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrmUserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrmUserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplipack.TagID.App.Resources.FormMessages.FrmUser.FrmUserMessages", typeof(FrmUserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Usuários | Ação: Adicionado | Nome Completo: {1}, Nome de Usuário: {2}, Nível de Acesso: {3}, {4}.
        /// </summary>
        internal static string ADD_USER_LOG {
            get {
                return ResourceManager.GetString("ADD_USER_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do usuário fora do padrão..
        /// </summary>
        internal static string BTN_SAVE_USER_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_SAVE_USER_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha fora do padrão..
        /// </summary>
        internal static string BTN_SAVE_USER_TEXT_2 {
            get {
                return ResourceManager.GetString("BTN_SAVE_USER_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome/Login fora do padrão..
        /// </summary>
        internal static string BTN_SAVE_USER_TEXT_3 {
            get {
                return ResourceManager.GetString("BTN_SAVE_USER_TEXT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string BTN_SAVE_USER_TEXT_4 {
            get {
                return ResourceManager.GetString("BTN_SAVE_USER_TEXT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário NÃO expira.
        /// </summary>
        internal static string BTN_USER_EXPIRE_TEXT_1 {
            get {
                return ResourceManager.GetString("BTN_USER_EXPIRE_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário expira.
        /// </summary>
        internal static string BTN_USER_EXPIRE_TEXT_2 {
            get {
                return ResourceManager.GetString("BTN_USER_EXPIRE_TEXT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desabilitado.
        /// </summary>
        internal static string BTN_USER_STATUS_1 {
            get {
                return ResourceManager.GetString("BTN_USER_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitado.
        /// </summary>
        internal static string BTN_USER_STATUS_2 {
            get {
                return ResourceManager.GetString("BTN_USER_STATUS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de senha incorreta.
        /// </summary>
        internal static string CONFIRM_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro do usuário {0} obtido para edição..
        /// </summary>
        internal static string DG_USER_TEXT_1 {
            get {
                return ResourceManager.GetString("DG_USER_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados incorretos.
        /// </summary>
        internal static string ERROR_TITLE {
            get {
                return ResourceManager.GetString("ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome completo deve ter no máximo 50 caracteres.
        /// </summary>
        internal static string FULLNAME_INVALID_LENGTH_MAX {
            get {
                return ResourceManager.GetString("FULLNAME_INVALID_LENGTH_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome completo deve ter no mínimo 5 caracteres.
        /// </summary>
        internal static string FULLNAME_INVALID_LENGTH_MIN {
            get {
                return ResourceManager.GetString("FULLNAME_INVALID_LENGTH_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira data válida no formato DD/MM/AA.
        /// </summary>
        internal static string INVALID_DATE_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Usuários | Ação: Carregado | Nome Completo: {1}, Nome de Usuário: {2}, Nível de Acesso: {3}, {4}.
        /// </summary>
        internal static string LOAD_USER_LOG {
            get {
                return ResourceManager.GetString("LOAD_USER_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu nível de acesso [{0}] não possui autorização para realizar todas as ação deste formulário.
        /// </summary>
        internal static string MSGBOX_ACTION_LIMITED_ALLOWED {
            get {
                return ResourceManager.GetString("MSGBOX_ACTION_LIMITED_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu nível de acesso [{0}] não possui autorização para realizar essa ação.
        /// </summary>
        internal static string MSGBOX_ACTION_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("MSGBOX_ACTION_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to não.
        /// </summary>
        internal static string NO_TEXT_1 {
            get {
                return ResourceManager.GetString("NO_TEXT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira os dados do usuário e senha..
        /// </summary>
        internal static string NULL_DATA_USER_PASS {
            get {
                return ResourceManager.GetString("NULL_DATA_USER_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não está no padrão estabelecido. Por favor, insira uma nova senha.
        /// </summary>
        internal static string PASSWORD_INCORRECT_FORMAT {
            get {
                return ResourceManager.GetString("PASSWORD_INCORRECT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter somente letras, números e os caracteres $*&amp;@#!.
        /// </summary>
        internal static string PASSWORD_INVALID_CHARACTERS {
            get {
                return ResourceManager.GetString("PASSWORD_INVALID_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter no máximo 20 caracteres.
        /// </summary>
        internal static string PASSWORD_INVALID_LENGTH_MAX {
            get {
                return ResourceManager.GetString("PASSWORD_INVALID_LENGTH_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter no mínimo 6 caracteres.
        /// </summary>
        internal static string PASSWORD_INVALID_LENGTH_MIN {
            get {
                return ResourceManager.GetString("PASSWORD_INVALID_LENGTH_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter ao menos uma letra minúscula.
        /// </summary>
        internal static string PASSWORD_MUST_CONTAIN_ONE_LOWERCASE_LETTER {
            get {
                return ResourceManager.GetString("PASSWORD_MUST_CONTAIN_ONE_LOWERCASE_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter ao menos um caractere especial.
        /// </summary>
        internal static string PASSWORD_MUST_CONTAIN_ONE_SPECIAL_CHARACTERS {
            get {
                return ResourceManager.GetString("PASSWORD_MUST_CONTAIN_ONE_SPECIAL_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter ao menos uma letra maiúscula.
        /// </summary>
        internal static string PASSWORD_MUST_CONTAIN_ONE_UPPERCASE_LETTER {
            get {
                return ResourceManager.GetString("PASSWORD_MUST_CONTAIN_ONE_UPPERCASE_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Usuários | Ação: Alterado | Nome Completo: {1}, Nome de Usuário: {2}, Senha {3}alterada, Nível de Acesso: {4}, {5}.
        /// </summary>
        internal static string SAVE_USER_LOG {
            get {
                return ResourceManager.GetString("SAVE_USER_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja mesmo atualizar cadastro do usuário?.
        /// </summary>
        internal static string UPDATE_USER_QUESTION {
            get {
                return ResourceManager.GetString("UPDATE_USER_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar usuário.
        /// </summary>
        internal static string UPDATE_USER_QUESTION_TITLE {
            get {
                return ResourceManager.GetString("UPDATE_USER_QUESTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} | Tela: Usuários | Ação: Clicou em {1}.
        /// </summary>
        internal static string USER_CLICK_LOG {
            get {
                return ResourceManager.GetString("USER_CLICK_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum acesso foi selecionado.
        /// </summary>
        internal static string USERACCESS_NONE {
            get {
                return ResourceManager.GetString("USERACCESS_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome de usuário já está sendo utilizado.
        /// </summary>
        internal static string USERNAME_IN_USE {
            get {
                return ResourceManager.GetString("USERNAME_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome de usuário deve ter no máximo 20 caracteres.
        /// </summary>
        internal static string USERNAME_INVALID_LENGTH_MAX {
            get {
                return ResourceManager.GetString("USERNAME_INVALID_LENGTH_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome de usuário deve ter no mínimo 4 caracteres.
        /// </summary>
        internal static string USERNAME_INVALID_LENGTH_MIN {
            get {
                return ResourceManager.GetString("USERNAME_INVALID_LENGTH_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome de usuário deve ter somente letras, números ou underline.
        /// </summary>
        internal static string USERNAME_INVALID_LOGIN {
            get {
                return ResourceManager.GetString("USERNAME_INVALID_LOGIN", resourceCulture);
            }
        }
    }
}
